### ISSUE TITLE
Question about async_std::fs::ReadDir

### ISSUE THREAD

**Issue by PHSix** [async-rs/async-std#1000]
I am a new user for `async-std`. Recently I want to wirte a program with rust `asycn-std` crate to achieve get all files under a directory. But I found that the `ReadDir` struct have no public methods to get `DirEntry` struct(Actually it have no public method.). At the same time, I found a example about use `async_std::fs::DirEntry` in `docs.rs`:
![image](https://user-images.githubusercontent.com/57695072/147844754-02688d2f-1574-4856-b567-f082eb35d5e9.png)
In this example, it use `next` method of `async_std::fs::ReadDir` struct. But actually the `next` method of `async_std::fs::ReadDir` struct is private.

**Comment by jbr** [comment]
ReadDir is Stream, and it is [Stream's next](https://docs.rs/async-std/latest/async_std/stream/trait.Stream.html#method.next) that the example uses for async iteration. You'll need to `use async_std::stream::Stream` in order to use it

**Comment by PHSix** [comment]
> ReadDir is Stream, and it is [Stream's next](https://docs.rs/async-std/latest/async_std/stream/trait.Stream.html#method.next) that the example uses for async iteration. You'll need to `use async_std::stream::Stream` in order to use it, which is included in the async_std prelude

Oh, thanks for your reply. I know where I take a mistake. Thanks for you again😎.
