### ISSUE TITLE
Please make a new release

### ISSUE THREAD

**Issue by piegamesde** [async-rs/async-std#1003]
It's been over a year since the last release. I depend on some newer changes, but AFAICT I cannot make a release on crates.io when having git dependencies.

**Comment by yoshuawuyts** [comment]
Yes, that's a good point! Our last release was a little over six months ago, but we agree it's about time we put out a new release. Let me coordinate with my fellow maintainers, but hopefully we should be able to put something out soon!

**Comment by piegamesde** [comment]
[Thank you](https://github.com/async-rs/async-std/releases/tag/v1.11.0)
