### ISSUE TITLE
Question: is awaiting `async_std::channel::recv` cancellation safe?

### ISSUE THREAD

**Issue by fprasx** [async-rs/async-std#1061]
I have some code that looks this:

```rust
#[async_std::main]
fn main() {
    tokio::select! {
        _ = channel.recv() => { ... }
        _ = other_future => { ... }
        _ = otherer_future => { ... }
    }
}
```
Is this safe? Thank you!

**Comment by yoshuawuyts** [comment]
The future returned by `recv` does not hold any future-local state, so it should be "cancellation-safe". That said I'd caution against using `select!`, and would recommend using combinators from [futures-concurrency](https://docs.rs/futures-concurrency/latest/futures_concurrency/) if possible.
