### ISSUE TITLE
Release 1.13.0?

### ISSUE THREAD

**Issue by polarathene** [async-rs/async-std#1081]
1.12.0 was [released in June 2022](https://github.com/async-rs/async-std/releases/tag/v1.12.0), it's been over 2 years.

[This issue](https://github.com/sunfishcode/io-lifetimes/issues/38) is tracking crates with `async-std` as one blocker waiting on a release for a [`async-std` PR that was merged back in May 2023](https://github.com/async-rs/async-std/pull/1036).

**Comment by Qix-** [comment]
Is this project even still active? It hasn't been published in two years, which is a little disheartening.

**Comment by polarathene** [comment]
> Is this project even still active?

[There is still commits every few months being merged to `main`](https://github.com/async-rs/async-std/commits/main/), so yes it's active.

Best we can do is wait until [one of the maintainers](https://github.com/orgs/async-rs/people) is willing to tackle putting out a new release. There can be some friction to doing that, especially with such a long gap since the last one, but if that's a concern perhaps they could express what needs to be done that a contributor could help push forward.

A friendly ping to recently active maintainers on the project may get some attention if you're lucky. @dignifiedquire @Keruspe @Fishrock123

Only one of those maintainers pinged has frequent Github activity, they've likely got quite a lot going on. The other two are less likely to notice / respond to the ping from the lack of activity though 😅

**Comment by Keruspe** [comment]
Let's see how #1083 goes

**Comment by Keruspe** [comment]
Well, at least https://github.com/async-rs/async-std/pull/1036#issuecomment-2299720749 will need addressing first

**Comment by sunfishcode** [comment]
I've now submitted https://github.com/async-rs/async-std/pull/1084 to address https://github.com/async-rs/async-std/pull/1036#issuecomment-2299720749.

**Comment by Keruspe** [comment]
I've fixed a few follow-up problems, CI is now green

**Comment by jayvdb** [comment]
https://github.com/async-rs/async-std/pull/1083 is preparing the release, but it hasnt happened yet.

**Comment by Keruspe** [comment]
Ah, haven't created it on GitHub indeed, but it's on crates.io
