### ISSUE TITLE
Missing tag + release notes for 1.13

### ISSUE THREAD

**Issue by zeenix** [async-rs/async-std#1093]
It was very great to see a release of async-std after 2 years. It's good to know that the project is alive and kicking.

However, I noticed that the tag and release from the repo are missing. It would be great to have those, so people know what changed after 1.12.

**Comment by Keruspe** [comment]
Sorry about that, fixed

**Comment by zeenix** [comment]
> Sorry about that, fixed

Np. Thanks for making the release happen!
