### ISSUE TITLE
Misleading future documentation?

### ISSUE THREAD

**Issue by ambiso** [async-rs/async-std#110]
Hi,

the async-std documentation hints that there is a join futures combinator, but according to issue #14 this is still missing: [link](https://docs.rs/async-std/0.99.4/async_std/future/trait.Future.html#impl-Future-for-Join%3CFut1%2C%20Fut2%3E).

I recognize that this may be an issue of lower importance, and might not be trivial to fix. Feel free to close this issue if this won't be fixed.

Best,
ambiso

**Comment by Wassasin** [comment]
Now that #14 is closed, this issue can be closed as well.
