### ISSUE TITLE
Implement Stream::size_hint

### ISSUE THREAD

**Issue by yoshuawuyts** [async-rs/async-std#128]
Equal to https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.size_hint. Don't think this needs to be marked `async`. This would've been useful to calculate the right pre-alloc size for calling `collect` into a vec in #125. Thanks!

**Comment by taiki-e** [comment]
Could you explain the value of `size_hint` that cannot be implemented manually?

**Comment by yoshuawuyts** [comment]
@taiki-e I feel its mostly API consistency? With iter size hint it's useful when pre-allocating structures. For example when using `collect` for vec it would've been useful to get an estimate of how much to allocate. Right now we start with an empty vector and allocate as we go, which is not nearly as efficient as it could be.

**Comment by taiki-e** [comment]
The problem is that `size_hint` always returns the default value because `async_std::stream::Stream` cannot be implemented manually. So, currently, calling `size_hint` for optimization is a needless operation.

**Comment by taiki-e** [comment]
IMO, we should wait for [the upstream to add size_hint](https://github.com/rust-lang-nursery/futures-rs/issues/170), instead of adding such a “useless API”.

**Comment by yoshuawuyts** [comment]
@taiki-e ah yeah, fair point.

Though I don't disagree, I do see value in implementing all APIs sooner rather than later though. This way we can have the external API that folks can call, which can be incorporated in app logic — and later when we fix the impl nobody needs to rewrite their code.

Or well, that's the theory.

**Comment by yoshuawuyts** [comment]
Yay, https://github.com/rust-lang-nursery/futures-rs/pull/1853 landed!

**Comment by yoshuawuyts** [comment]
We're now blocked on `futures-preview@0.3.0-alpha.19` landing to implement this.

**Comment by yoshuawuyts** [comment]
Sweet, this has landed! This means we can now rely on `size_hint` for optimizing allocations in `FromStream` impls!

cc/ @sunjay
