### ISSUE TITLE
Add possibility to configure the way tasks are spawned

### ISSUE THREAD

**Issue by tomaka** [async-rs/async-std#137]
The `async_std::task::Builder` and `async_std::task::spawn` methods assume that some kind of environment is present (ie. a background thread pool) where to spawn tasks.

https://github.com/async-rs/async-std/blob/532c73cf77a762e34e6fbafb9be9e7ff0bd66c78/src/task/pool.rs#L172-L192

Crates that provide some sort of hidden environment generally provide a way to configure how it works. Example of what I mean:

- https://doc.rust-lang.org/nightly/std/panic/fn.set_hook.html
- https://docs.rs/futures-timer/0.3.0/futures_timer/struct.TimerHandle.html#method.set_as_global_fallback
- https://docs.rs/log/0.4.8/log/fn.set_logger.html
- https://github.com/rust-lang/rust/issues/31343

Similarly, I think `async_std` should provide some sort of `set_task_spawner` function that allows configuring how that works.

The use-case I have in mind is the browser environment, where you want to drive tasks by using [`spawn_local`](https://docs.rs/wasm-bindgen-futures/0.3.27/wasm_bindgen_futures/fn.spawn_local.html) (which is implemented using `setTimeout`).

**Comment by yoshuawuyts** [comment]
@tomaka on phone right now — but would perhaps an acceptable short-term solution to your issue be to allow `async-std` to work in the browser?

**Comment by tomaka** [comment]
> short-term solution

It's not urgent at all!
My browser experiments work by merging everything into a single future. I don't spawn anything in the background.

**Comment by sdroege** [comment]
See also https://github.com/async-rs/async-std/issues/79, which is kind of related but broader.

**Comment by yoshuawuyts** [comment]
As this is mostly already covered by https://github.com/async-rs/async-std/issues/79, I'm going to go ahead and close this issue. We should continue to gather input on what folks want to configure and report it back in https://github.com/async-rs/async-std/issues/79.

Thanks all!
