### ISSUE TITLE
Change the timeout API?

### ISSUE THREAD

**Issue by stjepang** [async-rs/async-std#18]
Timeouts are confusing. @spacejam recently wrote an example that contains the following piece of code:

```rust
stream
    .read_to_end(&mut buf)
    .timeout(Duration::from_secs(5))
    .await?;
```

The problem here is that we need two `?`s after `.await` and it's easy to forget that.

I think the confusing part is in that the `.timeout()` combinator looks like it just *transforms* the future in a similar vein to `.map()` or `.and_then()`, but it really does not!

Instead, `.timeout()` *bubbles* the result of the future so that its type becomes `Result<Result<_, io::Error>, TimeoutError>`.

Perhaps it would be less confusing if `timeout()` was a free-standing function in the `future` module rather than a method on the `time::Timeout` extension trait?

```rust
future::timeout(
    stream.read_to_end(&mut buf),
    Duration::from_secs(5),
)
.await??;
```

This `timeout()` function would stand alongside `ready()`, `pending()`, and maybe some other convenience functions in the `future` module.

Here's another idea. What if we had `io::timeout()` function that resolves to a `Result<_, io::Error>` instead of bubbling the results? Then we could write the following with a single `?`:

```rust
io::timeout(
    stream.read_to_end(&mut buf),
    Duration::from_secs(5),
)
.await?;
```

Now it's also more obvious that we're setting a timeout for an I/O operation and not for an arbitrary future.

In addition to that, perhaps we could delete the whole `time` module? I'm not really a fan of it because it looks nothing like `std::time` and I generally dislike extension traits like `Timeout`.

Note that we already have a time-related function, `task::sleep()`, which is not placed in the `time` module so we probably shouldn't worry about grouping everything time-related into the `time` module. I think it's okay if we have `io::timeout()` and `future::timeout()`.

Finally, here's a really conservative proposal. Let's remove the whole `time` module and only have `io::timeout()`. A more generic function for timeouts can then be left for later design work. I think I prefer this option the most.

**Comment by sdroege** [comment]
> What if we had `io::timeout()` function that resolves to a `Result<_, io::Error>` instead of bubbling the results?

In addition to the current variant? IMHO the current variant is useful on its own for non-IO futures too. You might have some more complicated user defined futures (which might or might not be around IO futures) that don't return a plain `io::Error` but some more complex error type (that might contain an `io::Error` variant somewhere though).

Removing the current variant would seem suboptimal to me.

**Comment by DoumanAsh** [comment]
Just as example I prefer timeouts that allow me to restart and retrieve original future on failure:

`pub fn timed<F: Future>(job: F,  timeout: Duration) -> impl Future<Output = Result<F::Output, Expired<F, Timer>>>`
And without any extra error from timer itself 😄

**Comment by stjepang** [comment]
@DoumanAsh If `fut` is a `Future`, then `&mut fut` is also a `Future`, so you can pass a `&mut fut` to the timeout function and continue using `fut` if timeout occurred.

Unless I'm missing something, there's not much reason to return the original future since one can use a mutable borrow of the future. Do you agree with that assessment?

**Comment by DoumanAsh** [comment]
It is indeed true, that with `&mut F` you could get around it.
But it applies severe restriction on `F`, it must be `Unpin` always then, which is not true for `async fn` and it is not clear whether it will change (Boxing is work around, not a solution)

**Comment by stjepang** [comment]
> But it applies severe restriction on `F`, it must be `Unpin` always then

Is that not true also for the case when the timeout function returns the original future back to the user? If `F` has self-references and gets polled by the timeout function, and is then returned back, returning moves the future and therefore invalidates self-references.

**Comment by yoshuawuyts** [comment]
The original issue has been resolved, and conversation has settled down. I'm going to go ahead and close this for now (:
