### ISSUE TITLE
Is there a http library/server build on async-std?

### ISSUE THREAD

**Issue by zmlzm** [async-rs/async-std#191]
Is there a http library/server build on async-std?
or Are you a plan for it?

**Comment by yoshuawuyts** [comment]
There's a few projects started:

- https://github.com/mgattozzi/hidouki
- https://github.com/dignifiedquire/h1/

And I also have something I've been trying out. But it's still early days for HTTP on top of `async-std` for sure.

**Comment by xldenis** [comment]
I think this is worth re-opening, both those projects seem dead. And `tide` the web framework linked in the homepage drags in `hyper` (and tokio) to serve requests. It'd be nice to write apps that don't require _both_ major async runtimes to run :P
