### ISSUE TITLE
add `try_clone` for `TcpStream`

### ISSUE THREAD

**Issue by DCjanus** [async-rs/async-std#193]
Just like this: https://doc.rust-lang.org/std/net/struct.TcpStream.html#method.try_clone

**Comment by stjepang** [comment]
I wonder: is there a situation where this method is more useful than using `Arc<TcpStream>` and cloning it?

**Comment by yoshuawuyts** [comment]
@stjepang to my understanding `Arc<TcpStream>` will not send all data to all listeners -- e.g. if bytes are read from any one `TcpStream`, they will no longer be available from the other. Instead using a dedicated `try_clone` impl ensures that all clones receive _all_ data.

**Comment by stjepang** [comment]
> Instead using a dedicated `try_clone` impl ensures that all clones receive _all_ data.

Hmm, doesn't `try_clone()` create another reference to the same stream? I thought on Linux it's implemented as a call to `dup(fd)`, which probably just bumps a reference counter in the kernel (just like we'd clone the `Arc` here).

**Comment by DCjanus** [comment]
For some reason, I replied after so long, sorry for that.

I'm a Chinese Xbox player, for some reason, I can't download those games quickly. And Xbox didn't supported socket5 or HTTP proxy, but you can set custom DNS address. I'm trying to hijacking DNS queries and pack all TCP data into my Socks5 proxy, with higher speed.

Which means, I should make those happen in my Rust programming: listen 443 and 80 port on my PC; accept connections from my Xbox(which I called `origin connection`); find domain in SNI; connect to remote server through my Socks5 proxy(which I called `upstream connection`).

Which means, I should read data from `origin` and write them to `upstream`, and I have to read data from `upstream` and write them to `origin`.

There are some functions like `futures::AsyncReadExt::copy_into`, code in my mind should be like this:

```Rust 
origin.copy_into(&mut upstream);
upstream.copy_into(&mut origin);
```

But, obviously, borrow check told me: 'you can't'.

I'm not sure if I understand what you mean correctly(about `Arc<TcpStream>`), but it seems that TcpStream required `&mut self` and `Arc` not work for that.

If I misunderstood what you mean, please let me know.

**Comment by stjepang** [comment]
> ```rust
> origin.copy_into(&mut upstream);
> upstream.copy_into(&mut origin);
> ```

Can you try this?

```rust
origin.copy_into(&mut &upstream);
upstream.copy_into(&mut &origin);
```

Note that `&TcpStream` implements `AsyncRead + AsyncWrite`, just like `TcpStream` does.

**Comment by DCjanus** [comment]
It works! Thank you!

```Rust
let mut origin = Arc::new(origin);
let upstream = Arc::new(upstream);

let origin_reader:&TcpStream = &origin;
let origin_writer:&mut &TcpStream = &mut &*origin;
let upstream_reader:&TcpStream = &upstream;
let upstream_writer:&mut &TcpStream = &mut &*upstream;

origin_reader.copy_into(upstream_writer);
upstream_reader.copy_into(origin_writer);
```

Shorter but more confusing:

```Rust
let mut origin = Arc::new(origin);
let upstream = Arc::new(upstream);

(&*origin).copy_into(&mut &*origin);
(&*upstream).copy_into(&mut &*origin);
```
