### ISSUE TITLE
async_std::Stream interracts badly with futures::select!

### ISSUE THREAD

**Issue by matklad** [async-rs/async-std#23]
`futures::select!` requires that the streams selected over implement `futures::FusedStream`. There's a `.fuse()` method on `futures::StreamExt` which fuses any stream. The problem is, to use `StreamExt::fuse` on has to import this trait, and then the `.next` method collides between `async_std::Stream` and `futures::StreamExt`. 

See also https://github.com/async-rs/a-chat/pull/1#discussion_r313992663

**Comment by yoshuawuyts** [comment]
We now have [async-macros](https://docs.rs/async-macros/1.0.0/async_macros/) which has `stream::join` that allows bypassing the problems `futures_preview::select` has.

The pattern is to define an enum of event kinds, and then map each individual stream to be a member of that enum. Then using async iteration + `match` the same semantics can be achieved as `futures_preview::select`.

Going to go ahead and close this!
