### ISSUE TITLE
Use GitHub Actions

### ISSUE THREAD

**Issue by yoshuawuyts** [async-rs/async-std#246]
[actions-rs](https://github.com/actions-rs) by @svartalf has been looking fantastic, and I think we should consider using it instead of Travis.

For example today [actions-rs/clippy](https://github.com/actions-rs/clippy-check) was released, which places clippy checks inline in the PR review:

![screenshot](https://user-images.githubusercontent.com/2467194/65774660-ff5cbb00-e13e-11e9-8c1d-13a819039bf6.png)

I think some really good work is being done as part of `actions-rs`, and by using it we'll probably enjoy faster build times thanks to GitHub actions providing more cycles, and a chance to help Rust tooling development by being able to provide feedback / patches back to a very promising project.

The only open question I have is how this would integrate with Bors, if at all.

**Comment by taiki-e** [comment]
> The only open question I have is how this would integrate with Bors, if at all.

Related: https://github.com/bors-ng/bors-ng/issues/730 (Doesn't seem to be officially supported)

**Comment by yoshuawuyts** [comment]
Example of the clippy checks in action: https://github.com/actions-rs/example/pull/2/files.

**Comment by k-nasa** [comment]
Isn't it possible to use it with such a change?
https://github.com/samueldple/date_time/pull/45/files#diff-2f8c9db9253b64f9a332c09f492cd54e

**Comment by yoshuawuyts** [comment]
@k-nasa oh yeah, probably! -- is this something you'd like to try spinning up for our repo?

**Comment by k-nasa** [comment]
I'll try it! Can you assigne me?

**Comment by freebroccolo** [comment]
> Example of the clippy checks in action: https://github.com/actions-rs/example/pull/2/files.

[Here](https://github.com/freebroccolo/interfaces/blob/master/.github/workflows/main.yml) is an example of a configuration I'm using that might be useful.

The tarpaulin step takes the longest but there is a [PR](https://github.com/actions-rs/tarpaulin) at [actions-rs/tarpaulin](https://github.com/actions-rs/tarpaulin) that downloads the binary instead of building it and uses the tools cache. Should be much faster.

**Comment by svartalf** [comment]
It is a closed issue, but I would like to add a late comment: as soon as Github will add proper caching for Actions (AFAIK, mid-November), we try to add caching for installed binaries too; so the first one `cargo install` will be slow as usual, but the next installations of the same version will use the pre-compiled binary from cache. That would reduce time for all builds, which are installing something.

**Comment by taiki-e** [comment]
@yoshuawuyts 
FWIW, I have confirmed that GitHub Actions can integrate correctly with Bors.
https://github.com/taiki-e/pin-project/pull/117/files#diff-3515bd2b4297af2de6456cf6df7c9f4cR1-R10

**Comment by yoshuawuyts** [comment]
@taiki-e oh that's awesome; thanks so much for sharing that!
