### ISSUE TITLE
unix sockets don't work since the 0.99.6 release

### ISSUE THREAD

**Issue by dvc94ch** [async-rs/async-std#248]
Expected behaviour:
```sh
loop
connected
loop
```
Actual behaviour:
```sh
loop
```
`server.rs`
```rust
use async_std::prelude::*;
use async_std::os::unix::net::UnixListener;
use async_std::task;

async fn run() {
    let socket = UnixListener::bind("/tmp/test.sock").await.expect("bind");
    let mut incoming = socket.incoming();
    loop {
        println!("loop");
        if let Some(stream) = incoming.next().await {
            println!("connected");
        }
    }
}

fn main() {
    task::block_on(run());
}
```
`client.rs`
```rust
use async_std::task;
use async_std::prelude::*;
use async_std::os::unix::net::UnixStream;

async fn run() {
    let mut socket = UnixStream::connect("/tmp/test.sock").await.expect("connect");
    socket.write_all(b"hello world").await.expect("write");
    socket.flush().await.expect("flush");
}

fn main() {
    task::block_on(run());
}
```

**Comment by zvkemp** [comment]
Git bisect points to d25dae54191c8a922410cd2e3ca39e631d28982b

**Comment by mvucenovic** [comment]
Hey @stjepang, @yoshuawuyts I hope you don't mind me taking a stab at this.

I've debugged this issue (thanks @dvc94ch for the code that reproduces it), and I think I've found the cause of the bug, but my solution for it is short and hacky, so I need some guidance from you guys. I'll send a PR so you can take a look.

Also, I would like to add a bigger integration test that would cover this issue for the future, if you are okay with that.
