### ISSUE TITLE
How to read and write of TcpStream simultaneously in 2 task?

### ISSUE THREAD

**Issue by mineralres** [async-rs/async-std#261]
is there any examples?  like split in tokio:
`fn split(self) -> (ReadHalf<Self>, WriteHalf<Self>)
  where Self: AsyncWrite { ... }`
then i can read or write in two future simultaneously.

**Comment by yoshuawuyts** [comment]
@mineralres Good question! -- we've written about this in [our book](https://book.async.rs/patterns/small-patterns.html#splitting-streams):

```rust
use async_std::{io, net::TcpStream};
async fn echo(stream: TcpStream) {
    let (reader, writer) = &mut (&stream, &stream);
    io::copy(reader, writer).await;
}
```

Hope this helps!
