### ISSUE TITLE
0.99.7 crates.io upload is not consistent with the repo state

### ISSUE THREAD

**Issue by MOZGIII** [async-rs/async-std#274]
I'm having an error that seems to be fixed at `0.99.7` tag. Can you please audit the crates.io package state? I'd recommend yanking it if the inconsistency is confirmed.

**Comment by MOZGIII** [comment]
The issue is with `0.99.7` version.

**Comment by yoshuawuyts** [comment]
We merged the release prep in #239, and cut the release the same date in https://github.com/async-rs/async-std/releases/tag/v0.99.7. The release tag points to the merge commit of the PR.

I'm not sure how to review whether the release on crates.io matches the release tag. Could you perhaps share more details on how we can check this?

**Comment by MOZGIII** [comment]
I created this repo: https://github.com/MOZGIII/async-std-issue-274
It captures the core problem. `cargo +nightly test` fails with the following:
```
...
error[E0599]: no method named `initializer` found for type `std::pin::Pin<&mut R>` in the current scope
  --> /home/mozgiii/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-0.99.7/src/io/read/read_to_end.rs:67:20
   |
67 |                 rd.initializer().initialize(&mut g.buf[g.len..]);
   |                    ^^^^^^^^^^^ method not found in `std::pin::Pin<&mut R>`
   |
   = help: items from traits can only be used if the trait is implemented and in scope
   = note: the following trait defines an item `initializer`, perhaps you need to implement it:
           candidate #1: `std::io::Read`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
error: could not compile `async-std`.

To learn more, run the command again with --verbose.
```

**Comment by yoshuawuyts** [comment]
Ah yes, this problem was fixed in `0.99.8`! -- We published this a few days after `0.99.7` specifically to address this problem. This is happening because `futures-preview` updated to change the `initializer` argument, so we pinned it to `alpha.18`.

The next release will upgrade `futures-preview` version to `alpha.19` so we can build on beta as well.

**Comment by MOZGIII** [comment]
In the repo there's a fix for this exact issue: https://github.com/async-rs/async-std/blob/6fe958f745741ae887ac1dd27e9e66e4986e3388/src/io/read/read_to_end.rs#L67

On the other hand, it's in `master`, but not at `v0.99.7` tag. This is confusing, cause I believe `cargo` had to build the code before release is uploaded, and I wonder how that worked.

So, nvm.

**Comment by MOZGIII** [comment]
I'm looking forward to the release with support for `0.3.0-alpha.19`.

**Comment by yoshuawuyts** [comment]
@MOZGIII Same! There should be one going out next week!
