### ISSUE TITLE
Reduce dependency on futures_timer 

### ISSUE THREAD

**Issue by yoshuawuyts** [async-rs/async-std#275]
In preparation for #170, we should reduce the API surface of any new dependency and make it easier to swap between implementations.

To that extent it's probably best if we only rely on [`futures_timer::Delay`](https://docs.rs/futures-timer/0.4.0/futures_timer/struct.Delay.html), and remove our dependency on other parts of the `futures-timer` crate.

Once that's done we can vastly reduce the API surface of `futures-timer` itself, and then create a new crate that implements the same (much smaller) API surface.

This should be reasonably straight forward, and fairly easy to pick up. So this is marked as "good first issue". If someone wants to pick this up it'd be greatly appreciated!

## Tasks
- [x] [`src/io/timeout.rs`](https://github.com/async-rs/async-std/blob/master/src/io/timeout.rs#L3) remove dependency on `futures_timer::TryFutureExt` by inlining the logic.

**Comment by shaikh-raj** [comment]
Can I pick this one?

**Comment by yoshuawuyts** [comment]
@shaikh-raj for sure! Thanks for volunteering!

**Comment by yoshuawuyts** [comment]
@shaikh-raj wanted to briefly check in with how are things going :sparkles: -- no rush at all, but want to make sure you're not stuck either!
