### ISSUE TITLE
FromStream module-level documentation

### ISSUE THREAD

**Issue by yoshuawuyts** [async-rs/async-std#276]
Now that #271 has been merged we have all of our `FromStream` implementations! The final touch for this is to add module-level documentation to `async_std::stream::FromStream` so we can teach people about how `FromStream`, `IntoStream` and `collect` work together.

In practice this means porting the [`std::iter::FromIterator`](https://doc.rust-lang.org/std/iter/trait.FromIterator.html) docs, and replacing it with our `Stream` code. The only caveat would be that `IntoStream` is currently not implemented on any types because of the orphan rules. Though I don't believe that should be a blocker for these set of of docs.

I'm marking this as "good first issue" because it should be relatively straight forward to implement, and is a good opportunity to contribute to async-std!

Ref #129.

**Comment by k-nasa** [comment]
The issue should close?
