### ISSUE TITLE
Add UdpSocket::PeerAddr

### ISSUE THREAD

**Issue by yoshuawuyts** [async-rs/async-std#307]
This was just stabilized in std; we should consider adding it too.

https://github.com/rust-lang/rust/pull/64728

**Comment by ansrivas** [comment]
@yoshuawuyts I quickly looked in the source code, please correct me if I am wrong, this is going to be currently blocked by mio's new release with `peer_addr` implementation right?

**Comment by yoshuawuyts** [comment]
@ansrivas yeah I guess you're right.

**Comment by zhaxzhax** [comment]
I am a beginner in Rust. And I am really delighted to see there is a issue I can fix. I am gonna take this one.

**Comment by humancalico** [comment]
@yoshuawuyts It seems like this can be closed now.
