### ISSUE TITLE
Add Flow API

### ISSUE THREAD

**Issue by vertexclique** [async-rs/async-std#36]
Currently, we have `Stream` API implementation. For async processing of incoming data, we can add `Flow` API.

### Use case 1
Imagine I have a stream like this:
```rust
let mut k = stream::cycle(vec![1, 2, 3]);
```

I want to dispatch events to different processing stages. Like I want to add all `1`s, multiply all `2`s etc.

There is no convenient way to do that except initially creating different streams for them.
This is what I call `partition`.

### Use case 2
Then I want to merge these and create a unified stream.

Process things in this merged stream and continue doing it.
This is what I call `merge` and `priority selection based merge`.

### Use case 3

I want to create fully replicated streams from a single stream.
That I call `broadcast`.

## Benefits
* This API will ease the pain of continuous async processing of events.
* Allow stream combinators without any extra overhead and built-in trust to this library.
* Allow putting further abstractions on top of network programming blocks. (Which is going to be super nice)

**Comment by kellytk** [comment]
@skade Could https://github.com/Pauan/rust-signals be relevant to `async-std`?

**Comment by skade** [comment]
@kellytk At a glance, it looks good! Certainly not within the lib, but it would be great to join forces and come up with something nice.

**Comment by kellytk** [comment]
@Pauan How do you think https://github.com/Pauan/rust-signals and `async-std` could best be used together?
