### ISSUE TITLE
Unnecessary PathBuf allocation for fs functions

### ISSUE THREAD

**Issue by svartalf** [async-rs/async-std#374]
`async_std::fs` functions are allocating new `PathBuf` from the incoming `path` parameter (line 39 in the example below):

https://github.com/async-rs/async-std/blob/ec23632f3e7d2d8f9ed49995b85741eeb0a5be69/src/fs/read_to_string.rs#L38-L41

It is unnecessary when `path` is owned type already like `PathBuf` or `String`.
I do understand it is done that way in order to move it later to the closure which will be sent to another thread, but is there maybe some way to improve that?

**Comment by stjepang** [comment]
Maybe if there was specialization we could do it, but I don't see any other solution right now :(

**Comment by yoshuawuyts** [comment]
I don't think there's much we can do here without specializations. My hope with this has always been that LLVM is (or becomes) smart enough to realize we're doing a redundant copy and optimizes it away in most cases. But other than that I'm not sure what we can do.

Going to go ahead and close this, as improving this is very much something that needs to happen at the compiler layer.
