### ISSUE TITLE
please add HTTP module to async-std

### ISSUE THREAD

**Issue by wu-jun-jie** [async-rs/async-std#382]
Every http impl need a runtime, now there is hyper, actix-http. 
more rust async runtime appear, then need write new http impl(or port/adapt the above one), This is painful, Hard to choose and compare.
please add HTTP module to async-std

**Comment by yoshuawuyts** [comment]
@wu-jun-jie we probably won't ever add an http implementation to `async-std` directly. But we hear you, and are definitely keen on making sure it's possible to make HTTP requests *with* `async-std`.

We don't have anything to share at this time, but this is pretty high up on our list. Thanks for opening!
