### ISSUE TITLE
Can not use async block or async fn in `async_std::future::select!`.

### ISSUE THREAD

**Issue by oblique** [async-rs/async-std#387]
I would expect this to work:

```rust
async fn foo() {
}

async_std::future::select!(foo(), async { });
```

**Comment by skade** [comment]
I see your point. The select macro is sadly limited by virtue of being a plain macro, let's see if we can fix this somehow.

I'd like to avoid using `proc_macro_hack` like `futures` does for this.

**Comment by k-nasa** [comment]
The same is true for join macros.
I thought the same thing, so I am very interested in how this is solved.

**Comment by yoshuawuyts** [comment]
What we've been talking about for a while now is to change the `select!` macros into regular methods. Unlike `join!` they don't have polymorphic output, which means it's mostly about maintaining parity with `join`. And to me that's started to become less appealing as an argument recently.

**Comment by paulocsanz** [comment]
Proc-macros compiled to web-assembly can help with this too without significant costs.

https://github.com/dtolnay/watt

**Comment by skade** [comment]
@paulocsanz Yes, but this is also heavily experimental and as such a compatibility hazard. It's fine, I believe the future can be found there, but let's talk once that became accepted practice.
