### ISSUE TITLE
Reading into a buffer from a file might stall the execution

### ISSUE THREAD

**Issue by andr2535** [async-rs/async-std#391]
When I try to run this test program, sometimes it stops executing after printing "Before".
I don't think the program should fail, so I'm creating this issue here.

```rust
use async_std::{fs::{File}, io::{prelude::*}};

fn main() {
    let mut some_buffer = vec!(0u8; 3);
    let file = std::fs::File::open("samplefile").unwrap();
    let mut file = File::from(file);

    async_std::task::block_on(async {
        println!("Before");
        file.read(&mut some_buffer).await.unwrap();
        println!("After");
    });
    println!("{:?}", some_buffer);
}
```
I run this example code using this infinite loop. Since it doesn't always occur.
```bash
while :; do cargo run --release; done
```

**Comment by stjepang** [comment]
I believe this is fixed on the master branch, we just need to publish a new version. Can you confirm?

You can use the master branch with the following in your `Cargo.toml`:

```toml
[dependencies]
async-std = { git = "https://github.com/async-rs/async-std" }
```

**Comment by andr2535** [comment]
Yes, I can confirm, it works correctly in the master branch.

Thanks :)
