### ISSUE TITLE
TCP smoke testing

### ISSUE THREAD

**Issue by yoshuawuyts** [async-rs/async-std#407]
Currently our system isn't running automated tests for TCP. We should at least have some smoke tests for:

- `async_std::net::TcpListener` + `std::net::TcpStream` (test tcp server)
- `async_std::net::TcpStream` + `std::net::TcpListener` (test tcp client)

There's an empty `tests/tcp.rs` file which we could use to fill in. This should be quite straight forward when basing it on the examples. The only tricky part would be how to do shutdown, but dropping a task should work well enough here (: Marking this as a good first issue!

**Comment by markhildreth** [comment]
It seems that `tests/tcp.rs` is not empty, but does already does have some tests in it, although none of them appear to be using the std library's `TcpStream`/`TcpListener`. To be more specific, are you looking for a test or two that has an async_std stream connect to a std listener, and a std listener connect to an async_std stream?

**Comment by markhildreth** [comment]
I've added #429 based on my assumption of the requirements. Please let me know if I've misunderstood the requirements. If so, I can make revisions.
