### ISSUE TITLE
Some questions about stream's methods

### ISSUE THREAD

**Issue by yjhmelody** [async-rs/async-std#410]
The streams have no bounds with Sized in some impls such as 
<https://github.com/async-rs/async-std/blob/master/src/stream/stream/max_by.rs#L33>

Others have the Sized bound, such as 
<https://github.com/async-rs/async-std/blob/master/src/stream/stream/min_by.rs#L33>

So are the Unpin.

Another question is that some impls such as `skip`, are using loop, while others are not, such as `min_by`
What's the different ?

**Comment by yoshuawuyts** [comment]
This seems to have been covered for our 1.0. release. Thanks for raising this!
