### ISSUE TITLE
remove pin-utils

### ISSUE THREAD

**Issue by yoshuawuyts** [async-rs/async-std#423]
Since #381 we've moved from pin-utils to pin-project-lite. We should finish that migration, and stop relying on pin-utils entirely.

**Comment by taiki-e** [comment]
pin-project{-lite} [doesn't support stack-pinning (pin_mut!)](https://github.com/taiki-e/pin-project/issues/58), so pin-utils still seems necessary.

**Comment by yoshuawuyts** [comment]
@taiki-e ah yeah, that makes sense. Thanks for clarifying!
