### ISSUE TITLE
rename Future::select to Future::race

### ISSUE THREAD

**Issue by yoshuawuyts** [async-rs/async-std#425]
Both JS and reactive streams use `race` for what we call `select`. So perhaps we should consider following suit.

This is after feedback from @withoutboats that the name may not be right.

**Comment by k-nasa** [comment]
I like this name Future::race. It's familiar to me, than select.

**Comment by yoshuawuyts** [comment]
I'll update #405 with this change.

**Comment by skade** [comment]
While I agree that `race` is a good name, I would not use familiarity and the JS API as an argument.

The reasoning is mainly that this requires the user to have a specific context (either being from the JS world or knowing the specifics of `select` vs `race`). We should also somehow make sure that people searching `select` may also find `race`.

**Comment by stjepang** [comment]
Related (here I talked about `select!` but it also applies to `select()`): https://github.com/rust-lang-nursery/futures-rs/issues/760#issuecomment-522719159

> We should also somehow make sure that people searching `select` may also find `race`.

I believe we could mention "select" in the docs of `race()` and then it would pop when searching for "select" in rustdoc.

**Comment by yoshuawuyts** [comment]
This was closed by https://github.com/async-rs/async-std/pull/405.
