### ISSUE TITLE
Expose future types from future::ready and future::pending

### ISSUE THREAD

**Issue by yoshuawuyts** [async-rs/async-std#453]
Today I was working on Tide, and came across the need for having the future type returned by `future::ready`. Namely I wanted to implement a no-op as part of a trait that expects a future to be returned.

The signature is:
```rust
    type ConnectionFuture: Future;

    fn connect(&self) -> Self::ConnectionFuture {
        ReadyFuture {}
    }
```

`fn connect` returns `ConnectionFuture`. It doesn't do anything, so using `future::ready` seemed like a nice option. Except since it's an async fn we're not able to enumerate it.

For this reason I'd like to propose exposing the futures from `future::ready` and `future::pending` so they can be used as no-ops, or thin wrappers and enumerated inside types. Thanks!

**Comment by stjepang** [comment]
Any reason why not use `Pin<Box<dyn Future<Output = ...>>>` or the `async-trait` crate?

This seems like the classic `async fn` in traits problem :)

**Comment by yoshuawuyts** [comment]
@stjepang I guess the answer is perf. But yeah maybe we just shouldn't. Unsure, heh.
