### ISSUE TITLE
non-prelude usage

### ISSUE THREAD

**Issue by Nemo157** [async-rs/async-std#455]
I was browsing the documentation today and noticed that there doesn't appear to be any way to use the extension methods without importing the prelude (e.g. `async_std::io::Read::read`). Is there a plan in place for providing access to these methods for users that avoid glob imports?

**Comment by stjepang** [comment]
I suggest we re-export extension traits in `async_std::prelude` without hiding them in docs and renaming with `as _`.

**Comment by dignifiedquire** [comment]
yes please, I have had multiple issues with those being hidden, when needing to distinguish between differnt imported traits.
