### ISSUE TITLE
Add Future::join and Future::try_join

### ISSUE THREAD

**Issue by yoshuawuyts** [async-rs/async-std#470]
Similar to #405's addition of `Future::race` we should expose `Future::join` and `Future::try_join` as well. However unlike #405 we would keep the macro around because it's the only way of creating a variable-sized tuple when joining multiple results ("return-type polymorphism").

This would be a chance as well to update the `future` module-level docs to talk about `Future::join` vs `Future::race`, making it more symmetrical.

This should be a fun challenge to pick up for whoever is interested. Marking it as "good first issue". Thanks!

**Comment by derekdreery** [comment]
I think this issue has been resolved?

**Comment by yoshuawuyts** [comment]
@derekdreery indeed it is. Thanks for pointing it out!
