### ISSUE TITLE
0.99.12 is a breaking change

### ISSUE THREAD

**Issue by leo60228** [async-rs/async-std#518]
Traits from futures-preview are considered different than the ones in futures, and are no longer implemented on async-std types. As 1.0, a version allowed to have breakage, has been released, should 0.99.12 be yanked?

**Comment by yoshuawuyts** [comment]
@leo60228 Hey, thanks for opening this. You're not wrong, `0.99.12` is indeed a breaking release. But unfortunately the same is true for every other version before it.

## How did our versioning work prior to 1.0.0?
The way we've done our pre-1.0 releases is not ideal. The semver spec says that `0.x.x` versions can introduce breaking changes by bumping their minor number. But we haven't quite done that; instead we've been releasing breaking changes by bumping our patch number as part of `0.99.x`. This is similar behavior as if we would be releasing `1.0.0-alpha.x` releases, but doesn't require opting in to the pre-release line of versions which seemed preferable to us.

We've been liberally publishing breaking changes in all versions before `1.0.0`, and while I'm sorry that the last patch has affected you, every version prior to that has introduced breaking changes. By virtue of being based on `futures-preview` which adopted the `-alpha.x` release strategy, we couldn't provide stability guarantees until now.

## Where to go from here
If you're unable to upgrade, consider pinning the version of `async-std` in your Cargo.toml. This may not work for all libraries, but should work for applications:

```rust
[dependencies]
async-std = "=0.99.11"
```

However, if possible, we'd strongly recommend upgrading to `async-std 1.0.0` which uses a stable version of `futures`, and will not be subject to the same volatility of our pre-release versions.

## Conclusion
We're sorry this has affected you. However hopefully this provides some insight into how our versioning used to work, how it currently works, and a possible mitigation strategy to minimize the effects this has until an upgrade is possible.
