### ISSUE TITLE
Cannot access the "Sender" of a channel

### ISSUE THREAD

**Issue by mrpink76** [async-rs/async-std#532]
I am having problems passing a sender as a parameter to a function.

The following code:

```rust
use async_std::sync::channel;
use async_std::io;
use async_std::prelude::*;
use async_std::task;


fn main() -> io::Result<()> {
    task::block_on(async {
        let (s, r) = channel::<i32>(1);
        let webcam = start_service(&s);
        Ok(())
    })
}

async fn start_service(s : &async_std::sync::channel::Sender<i32>) -> () {
}
```

gives the following error:
```
error[E0603]: module `channel` is private
  --> src\main.rs:15:46
   |
15 | async fn start_service(s : &async_std::sync::channel::Sender) -> () {
   |                                              ^^^^^^^
```

Is it an error or am I using it incorrectly?

Thanks for an awesome crate!

**Comment by dignifiedquire** [comment]
it is reexported at the top level `async_std::sync::Sender` should work.

**Comment by mrpink76** [comment]
Awesome! Thanks!

**Comment by yoshuawuyts** [comment]
@dignifiedquire is right; going to go ahead and close this issue.

However we should probably file a backlink from `Sender` and `Receiver` to `channel` so it becomes a bit more discoverable. Thanks!
