### ISSUE TITLE
max_by_key is wrong

### ISSUE THREAD

**Issue by wagnerf42** [async-rs/async-std#558]
hi, it seems to me that max_by_key is wrong.
i'm not 100% sure since I just started playing with futures and the error messages are kind of harsher than I'm used to.

the doc seems wrong to me : 
```rust
let s = stream::from_iter(vec![-1isize, -2, -3]);

let max = s.clone().max_by_key(|x| x.abs()).await;
assert_eq!(max, Some(3));
```
I would expect a max of -3 and not 3.
also in the source code, the MaxByKeyFuture has a key_by fn which returns a S::Item and not a B

**Comment by yoshuawuyts** [comment]
@wagnerf42 You're indeed correct, thanks for reporting. We've merged the patch in #559 and this should be fixed in the next release. Thanks heaps!
