### ISSUE TITLE
Add Future::timeout

### ISSUE THREAD

**Issue by yoshuawuyts** [async-rs/async-std#564]
Similar to [`future::timeout`](https://docs.rs/async-std/1.0.1/async_std/future/fn.timeout.html) and [`Stream::timeout`](https://docs.rs/async-std/1.0.1/async_std/stream/trait.Stream.html#method.timeout) we should add a `Future::timeout` method.

We already have `Future::delay`, and timeout would be a great counterpart. This is similar to stdlib's [`max`](https://doc.rust-lang.org/std/cmp/fn.max.html) which is both an inherent method and a free function. Thanks!

**Comment by miker1423** [comment]
I like to take this if no one is working on it.

**Comment by stjepang** [comment]
@miker1423 Go for it :)

**Comment by miker1423** [comment]
Sorry for the absence.
As I understood, I should add a new extension method to the Future trait?

**Comment by miker1423** [comment]
Here is the implementation https://github.com/miker1423/async-std/commit/c1f7be5d42f9fbeb63250e2b4f75986d2ae94fec, I know the docs are incomplete, I just wrote to take away the warning.

**Comment by yoshuawuyts** [comment]
@miker1423 yeah that's in the right direction. I don't believe the pub modifiers are needed; `pub(crate)` should suffice. If you could submit the PR it'd make it easier to review. Thanks heaps for your work1

**Comment by miker1423** [comment]
This should be closed with the merged PR #600, thanks!
