### ISSUE TITLE
Rewrite Barrier using WakerSet

### ISSUE THREAD

**Issue by yoshuawuyts** [async-rs/async-std#565]
The `broadcaster` library has taken us very far, but unfortunately has dependencies on `futures_channel`. Now that we have `WakerSet` available internally (for now still, see #549) we should probably consider rewriting `Barrier` to use it.

It should both improve our compilation times, and performance. This would put us in a place where we could consider stabilizing the API. Thanks!

cc/ @tmccombs @stjepang 

## Refs

- #369 
- #549 
- #440 
- #217

**Comment by tmccombs** [comment]
I can take a stab at this.

**Comment by leo60228** [comment]
You could implement `futures_sink::Sink` for `async_std::sync::Sender` to get rid of the `futures_channel` dependency. That would require committing to the `Sink` API in async-std, though.

**Comment by yoshuawuyts** [comment]
@leo60228 we have no plans to include `Sink` in `async-std` currently. I believe https://github.com/async-rs/async-std/pull/581 would close this issue, and is currently pending a review by @stjepang.

**Comment by tmccombs** [comment]
I wrote a standalone crate similar to WakerSet: https://github.com/tmccombs/waitlist. In fact it started out as just a separate crate for WakerSet, but then I had some ideas I wanted to try out it ended up rather different than the original WakerSet.
