### ISSUE TITLE
Make more errors verbose

### ISSUE THREAD

**Issue by killercup** [async-rs/async-std#569]
In #551 I added the ability to easily add details to `std::io::Error`s while not changing the type. This can make many error cases much more user friendly:

https://github.com/async-rs/async-std/blob/b3d30de4a11d785929a086e458ec1da4aec34bf3/src/fs/file.rs#L117-L118

I only added this in two places so far, though, `File::open` and `File::create`. Let's use this issue to track more places we should do this!

**Comment by gilescope** [comment]
Would love that std's errors could be just as helpful! Great work.

**Comment by killercup** [comment]
Thanks! That also reminds me: this issue can probably be closed by now. Feel free to enhance more errors of course!
