### ISSUE TITLE
The lib don't support IDE(vscode and Clion) auto-completion and Code hint

### ISSUE THREAD

**Issue by zys864** [async-rs/async-std#582]

**Comment by oribs1** [comment]
I think this is more of an IDE issue, intellij-rust (CLion) has a corresponding issue: https://github.com/intellij-rust/intellij-rust/issues/4627)

**Comment by SvetlinZarev** [comment]
It's an ide issue. You can try to switch to the experimental macro engine. It soved the issue for me:

Preferences -> Languages & Frameworks -> Rust -> Expand decl macros -> expand with experimental engine

**Comment by caibirdme** [comment]
@SvetlinZarev Followed your step, but it still doesn't work for me. (mac clion2019.2.1 rust1.39.0)

**Comment by ragona** [comment]
Thanks @SvetlinZarev -- that fixed the issue for me with Arch Linux and CLion 2019.3.
