### ISSUE TITLE
Throttle results in 100% cpu

### ISSUE THREAD

**Issue by tekjar** [async-rs/async-std#583]
```rust
use async_std::stream::StreamExt;
use async_std::sync::channel;
use async_std::task;

use std::thread;
use std::time::Duration;

#[async_std::main]
async fn main() {
    let (requests_tx, requests_rx) = channel::<i32>(10);
    let mut requests_rx = requests_rx.throttle(Duration::from_secs(1));

    thread::spawn(move || {
        task::block_on( async {
            for i in 0..5 {
                requests_tx.send(i).await;
            }
        });

        thread::sleep(Duration::from_secs(100));
    });

    while let Some(item) = requests_rx.next().await {
        println!("{:?}", item);
    }
}
```

![Screenshot from 2019-11-24 16-25-27](https://user-images.githubusercontent.com/6826529/69493704-fdfa0580-0ed7-11ea-9408-d7c666de58e0.png)

**Comment by yoshuawuyts** [comment]
I was able to reproduce this locally, uploaded a repro here: https://github.com/yoshuawuyts/repro-async-std-583.

**Comment by yoshuawuyts** [comment]
Confirmed that this happens in release mode too.

![2019-11-24-164539_1920x1080](https://user-images.githubusercontent.com/2467194/69497126-c4c29500-0ed9-11ea-8cbc-f922327a75dc.png)

I now suspect this is caused because `thread::sleep` is called, and our scheduler doesn't know how to handle that so it bounces the task around indefinitely. The spikes *seem* to be happening only once `thread::sleep` is hit.

**Comment by yoshuawuyts** [comment]
When applying this patch:

```diff
diff --git a/src/main.rs b/src/main.rs
index fa8dfed..b2d8e8a 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -8,7 +8,7 @@ use std::time::Duration;
 #[async_std::main]
 async fn main() {
     let (requests_tx, requests_rx) = channel::<i32>(10);
-    let mut requests_rx = requests_rx.throttle(Duration::from_secs(1));
+    let mut requests_rx = requests_rx.throttle(Duration::from_secs(10));
 
     thread::spawn(move || {
         task::block_on( async {
```

The output doesn't seem to spike, further corroborating the theory that this is caused by `thread::sleep` confusing the scheduler.

![2019-11-24-164752_1920x1080](https://user-images.githubusercontent.com/2467194/69497160-3864a200-0eda-11ea-9bfb-a242c26786b9.png)

**Comment by yoshuawuyts** [comment]
Okay, no it's not the threads happening. I think you're right and it's indeed something about debounce perhaps? Will run a flame graph next. 

Tested it with this patch, and got the same results:
```diff
diff --git a/src/main.rs b/src/main.rs
index fa8dfed..7c71e3a 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -2,7 +2,6 @@ use async_std::stream::StreamExt;
 use async_std::sync::channel;
 use async_std::task;
 
-use std::thread;
 use std::time::Duration;
 
 #[async_std::main]
@@ -10,14 +9,14 @@ async fn main() {
     let (requests_tx, requests_rx) = channel::<i32>(10);
     let mut requests_rx = requests_rx.throttle(Duration::from_secs(1));
 
-    thread::spawn(move || {
+    task::spawn(async move {
         task::block_on( async {
             for i in 0..5 {
                 requests_tx.send(i).await;
             }
         });
 
-        thread::sleep(Duration::from_secs(100));
+        task::sleep(Duration::from_secs(100)).await;
     });
 
     while let Some(item) = requests_rx.next().await {
```

![2019-11-24-165041_1920x1080](https://user-images.githubusercontent.com/2467194/69497196-8c6f8680-0eda-11ea-9c84-227d76ead599.png)

**Comment by yoshuawuyts** [comment]
Yes okay, if we remove the `throttle` call the problem indeed goes away.

```diff
diff --git a/src/main.rs b/src/main.rs
index fa8dfed..4839cc2 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -8,7 +8,7 @@ use std::time::Duration;
 #[async_std::main]
 async fn main() {
     let (requests_tx, requests_rx) = channel::<i32>(10);
-    let mut requests_rx = requests_rx.throttle(Duration::from_secs(1));
+    let mut requests_rx = requests_rx;
 
     thread::spawn(move || {
         task::block_on( async {
```

![2019-11-24-165347_1920x1080](https://user-images.githubusercontent.com/2467194/69497228-dc4e4d80-0eda-11ea-85bc-e4fa9944e59a.png)

**Comment by yoshuawuyts** [comment]
Okay, ran the flame graph locally, but nothing stands out really. It's a flat line it seems :sweat_smile: 

![2019-11-24-171658_1920x1080](https://user-images.githubusercontent.com/2467194/69497512-238a0d80-0ede-11ea-9eff-cddf557822f6.png)

**Comment by yoshuawuyts** [comment]
Okay, it seems that I forgot to remove the `task::block_on` call from `task::spawn` when I was testing that out. The CPU spikes go away if we remove it.

```diff
diff --git a/src/main.rs b/src/main.rs
index fa8dfed..ff7dae9 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -2,22 +2,19 @@ use async_std::stream::StreamExt;
 use async_std::sync::channel;
 use async_std::task;
 
-use std::thread;
 use std::time::Duration;
 
 #[async_std::main]
 async fn main() {
     let (requests_tx, requests_rx) = channel::<i32>(10);
-    let mut requests_rx = requests_rx.throttle(Duration::from_secs(1));
+    let mut requests_rx = requests_rx.throttle(Duration::from_secs(10));
 
-    thread::spawn(move || {
-        task::block_on( async {
-            for i in 0..5 {
-                requests_tx.send(i).await;
-            }
-        });
+    task::spawn(async move {
+        for i in 0..5 {
+            requests_tx.send(i).await;
+        }
 
-        thread::sleep(Duration::from_secs(100));
+        task::sleep(Duration::from_secs(100)).await;
     });
 
     while let Some(item) = requests_rx.next().await {
```

Seems like this might still be related to #358 ?

**Comment by tekjar** [comment]
```
thread::spawn(move || task::block_on(async {
        let requests_tx = requests_tx;
        for i in 0..10 {
            requests_tx.send(i).await;
        }

        task::sleep(Duration::from_secs(100)).await
    }));
```

Does this look like a legitimate use case? Looks so to me and cpu spikes in this case as well. `task::block_on` inside `thread::spawn` is a very similar case to using `task::block_on` in main. 

> using `block_on` and `thread::*` APIs inside of a task should be discouraged, and is definitely not using the APIs the way we intended it to

Sure. But in my head, worst case of using synchronous apis inside a cooperative eventloop should cause a block (and hence no progress), not cpu spikes.

**Comment by tekjar** [comment]
> @tekjar if you apply the patch above, the performance issues you experienced should go away (:

I doesn't to me. Maybe you throttle duration is very high (10 secs) and you are not waiting enough time?

**Comment by tekjar** [comment]
```rust
thread::spawn(move || {
    task::block_on( async {
            for i in 0..5 {
                requests_tx.send(i).await;
            }
    });

    thread::sleep(Duration::from_secs(100));
});
```

Is this pattern very weird in async world. To me, all the asynchronous code is encapsulated in `task::block_on`. I would've used `task::sleep` inside it. But using `thread::sleep` outside doesn't look like an anti pattern

**Comment by Matthias247** [comment]
Here is your busy-loop: https://github.com/async-rs/async-std/blob/50cefce803c88f3cd321b3bc181427b2bc4b30ce/src/stream/stream/throttle.rs#L59

The usage pattern of @tekjar looks fine to me. It's doing thread blocking operations in a thread, and not in a task.
