### ISSUE TITLE
`<TcpStream as Write>::poll_close` does nothing

### ISSUE THREAD

**Issue by twittner** [async-rs/async-std#599]
It seems that `<TcpStream as Write>::poll_close` [calls](https://github.com/async-rs/async-std/blob/bf9ee8881542cc4b8e06e07145f3fd5ae2807216/src/net/tcp/stream.rs#L340) `<&TcpStream as Write>::poll_close` which is a no-op. Would it not be more appropriate to shutdown the write direction of the socket, i.e. call `TcpStream::shutdown` with `std::net::Shutdown::Write`? Otherwise two processes that wait on each others EOF will wait forever.

**Comment by yoshuawuyts** [comment]
@twittner what you're suggesting seems reasonable; if you have the time, a patch for this would be greatly appreciated!
