### ISSUE TITLE
Allow unsized types for Mutex?

### ISSUE THREAD

**Issue by alekratz** [async-rs/async-std#609]
I'm trying to use a `dyn Trait` with a `Mutex` while moving from `std::sync::Mutex` to `async_std::sync::Mutex`. Is it possible for the `Mutex` in this crate to have `T: ?Sized`? The the std version allows for `?Sized` types, but I don't know if this would be an issue for async_std.

**Comment by yoshuawuyts** [comment]
@alekratz o/ thanks for raising! I'd love for us to take `?sized`, but am also unsure if that's possible. Currently nothing in `async-std` can take `?sized` so my guess is that it's tricky, if not outright impossible.

@nbdd0121 maybe you have a better perspective on this?

**Comment by yoshuawuyts** [comment]
Closed in #625. This will be part of the next release (probably `1.4.0`), due later this week. Thanks!
