### ISSUE TITLE
Readme example does not simply compile

### ISSUE THREAD

**Issue by kornelski** [async-rs/async-std#611]
My first impression of async-std was not positive. I've added it to the project, copy'n'pasted the first example, and I've got:

1. a compilation error
    ```
    2 | #[async_std::main]
      |              ^^^^ could not find `main` in `async_std`
    ```

2. and then noticed the explanation that the code used in the readme would be slow to compile. That makes it feel like it's not the best thing to use, and yet it's in the README.

It would be nicer if the first example in the README compiled with default crate features, without need to enable anything first. It's also worse by the fact that the prose just links to documentation that explains features. If the TOML markup enabling the required feature was inline in the README I'd have noticed it. But I didn't read the prose on purpose, since I wanted to jump straight to the code, and ended up disappointed.

**Comment by kornelski** [comment]
It's also confusing because surf crate has almost identical example, but it uses `#[runtime::main]` attribute instead. And `cargo add runtime` adds a wrong version (it picks only stable ones).

So the first two async examples I've tried both failed because of a mysteriously missing magical attribute around main.

**Comment by k-nasa** [comment]
@kornelski Thanks for open this issue!
This allowed me to notice documentation issues.

**Comment by i-schuetz** [comment]
I added `#[async_std::main]` to my main and it's also complaining with `could not find `main` in `async_std`. What's missing?

**Comment by zeljic** [comment]
> 
> 
> I added `#[async_std::main]` to my main and it's also complaining with `could not find main in async_std`. What's missing?

`async-std = {version = "1", features = ["attributes"]}`

**Comment by SergeiMinaev** [comment]
Examples in the documentation should be correct.
