### ISSUE TITLE
tests on master failing

### ISSUE THREAD

**Issue by yoshuawuyts** [async-rs/async-std#620]
Looks like #562 broke the tests; the double ended `from_iter` function was removed, and now tests on master are broken. https://github.com/async-rs/async-std/runs/347468653

cc/ @felipesere would you mind taking a look? Ideally `stream::FromIter` would implement: 

```rust
impl <T: DoubleEndedStream> DoubleEndedStream for FromIter<T>;
```

so that things just work.

**Comment by felipesere** [comment]
@yoshuawuyts this can be closed now? 😄 
Thanks for fixing it.

**Comment by skade** [comment]
Should be. Reopen if not true.
