### ISSUE TITLE
TCP request tasks not completing 

### ISSUE THREAD

**Issue by ragona** [async-rs/async-std#641]
I suspect I'm missing something simple, but I have a hacky test set up to make a batch of TCP requests, and I'm only seeing some seemingly random small number complete. (Say, if I try to make 100k I only see ~1500 complete.) 

I'm guessing that I'm not appropriately blocking on the future, but when I debug it I can see that each future is being executed to some degree. However, it isn't making it to the point that it actually does anything with the network as far as I can tell.

I'd love any assistance understanding what I'm missing here, and using a more idiomatic pattern! (In the future I'll make sure I'm not copying vectors all over the place, but for now I just wanted to understand the broad strokes.) 

```rust
use async_std::io::{self, Read, Write};
use async_std::net::TcpStream;
use async_std::prelude::*;
use async_std::task;

use futures::stream::FuturesUnordered;
use futures::StreamExt;

use crate::BenchConfig;

pub async fn request(url: &str, bytes: &[u8]) -> io::Result<()> {
    let mut buffer = [0u8; 1024];
    let mut stream = TcpStream::connect(url).await?;

    stream.write_all(bytes).await?;
    stream.read(&mut buffer).await?;

    Ok(())
}

pub fn load(config: BenchConfig, bytes: Vec<u8>) -> io::Result<()> {
    let mut futures = FuturesUnordered::new();
    for _ in 0..config.count {
        let config = config.clone();
        let bytes = bytes.clone();
        let future = async move {
            request(&config.url, &bytes).await;
        };

        futures.push(future);
    }
    
    // I'm guessing this isn't right? 
    task::block_on(async { while let Some(_) = futures.next().await {} });

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn it_works() {
        let m = "foo".as_bytes();
        load(
            BenchConfig {
                count: 1000,
                url: "0.0.0.0:8000".to_string(),
            },
            m.to_vec(),
        )
        .expect("oh no");
    }
}
```

**Comment by ragona** [comment]
I notice that the requests complete the way I'd hope they would if I replace the `UnorderedFutures` with this: 

```rust
    task::block_on(async {
        for t in tasks {
            t.await;
        }
    });
```

However, I think they're completing in order, and I'm not seeing the CPU cores utilized to the degree that I'd expect.

**Comment by ragona** [comment]
Oh, figured it out at least part of it. On this line:
```rust
let future = async move {
     request(&config.url, &bytes).await;
};
```

I actually wanted to give it to the task executor with:
```rust
        let task = task::spawn(async move {
```
Still some quirks to work out (and of course all of this works way better with a limited number of connections), but this is closer to what I expected.

**Comment by ragona** [comment]
Closing as user error. :)

**Comment by yoshuawuyts** [comment]
@ragona glad you were able to figure it out!
