### ISSUE TITLE
docs for UdpSocket::send have same example as send_to

### ISSUE THREAD

**Issue by killercup** [async-rs/async-std#652]
cf. https://docs.rs/async-std/1.4.0/async_std/net/struct.UdpSocket.html#method.send

**Comment by yoshuawuyts** [comment]
Heh, looks like this is similar to https://github.com/async-rs/async-std/pull/603 where we missed another PR.

**Comment by Noah-Kennedy** [comment]
If no one else is working on it, I think I might have a go at this one.

**Comment by Noah-Kennedy** [comment]
Fix should be ready for review.
