### ISSUE TITLE
Add TcpListener::shutdown

### ISSUE THREAD

**Issue by tomasol** [async-rs/async-std#653]
I would like to propose adding shutdown method similar to one found in `TcpStream`. 

Use case: in [tutorial](https://book.async.rs/tutorial/all_together.html) it would allow exiting from `accept_loop` without adding a shutdown channel.

**Comment by yoshuawuyts** [comment]
Reference: [`std::net::TcpListener::shutdown`](https://doc.rust-lang.org/std/net/struct.TcpStream.html#method.shutdown).

@tomasol I like this idea a lot, thanks for raising!

**Comment by yoshuawuyts** [comment]
@tomasol I agree this would be a great addition, but it probably should be added to `std` first -- we don't want to deviate from what's already provided, even if in some cases it'd be really convenient (such as here).

Thanks for opening this, but I don't think this is the right fit for us right now. Apologies for misreading the issue the first time around.

**Comment by leo-lb** [comment]
@tomasol https://github.com/rust-lang/rust/issues/67978

**Comment by leo-lb** [comment]
@tomasol https://github.com/rust-lang/rust/issues/67978#issuecomment-571687095

**Comment by tomasol** [comment]
@leo-lb thanks for the effort. In blocking case this might be difficult. 
@yoshuawuyts In non blocking case this should be doable, thus I believe the deviation is justifiable. I especially like the approach used in C# with cancellation tokens as shown [here](https://stackoverflow.com/a/23091920).

**Comment by leo-lb** [comment]
> @leo-lb thanks for the effort. In blocking case this might be difficult.
> @yoshuawuyts In non blocking case this should be doable, thus I believe the deviation is justifiable. I especially like the approach used in C# with cancellation tokens as shown [here](https://stackoverflow.com/a/23091920).

AFAIK C# futures are not the same as Rust futures. Rust futures are lazy, which means that if you don't want to execute them anymore, just stop polling them. To stop polling, as suggested previously to you on the other issue, you can use: https://docs.rs/async-std/1.4.0/async_std/future/trait.Future.html#method.race
