### ISSUE TITLE
Segfault in async-std/execu

### ISSUE THREAD

**Issue by serzhiio** [async-rs/async-std#662]
from /var/log/messages
```
Jan  6 22:14:40 c2-7-sbg3 kernel: [64693.609394] async-std/execu[28429]: segfault at 0 ip 00007faa146058b0 sp 00007faa0fbfb3d8 error 4 in libc-2.28.so[7faa144cf000+148000]
Jan  6 22:14:40 c2-7-sbg3 kernel: [64693.615905] Code: c2 83 e8 ff 75 04 c5 f8 77 c3 f3 0f bc c8 0f b6 04 0f 0f b6 14 0e 29 d0 c5 f8 77 c3 66 66 2e 0f 1f 84 00 00 00 00 00 0f 1f 00 <0f> 38 f0 07 0f 38 f0 0e 48 c1 e0 20 48 c1 e1 20 0f 38 f0 7c 17 fc
Jan  8 00:11:35 c2-7-sbg3 kernel: [158106.772220] traps: async-std/execu[25206] general protection ip:7f31d5cf724a sp:7f31d54eaf10 error:0 in libc-2.28.so[7f31d5c98000+148000]
```
I recieve just this in console with no backtrace
`Segmentation fault`
Any ideas?

**Comment by stjepang** [comment]
Can you do `cargo update` and try running again? The `async-crate` dependency got some fixes recently that might be related.

**Comment by serzhiio** [comment]
if you mean this:
```
   Compiling async-task v1.2.0
   Compiling async-std v1.4.0 (https://github.com/async-rs/async-std.git#383057b8)
```
updated just now...
but where is this error originated from? is it possible that it comes from my projects code?

**Comment by jmjoy** [comment]
How about run on another machine or build with target `musl`? I just meet the same problem but because the machine's `libc` is broken...

**Comment by serzhiio** [comment]
Here is my gdb log: https://gist.github.com/serzhiio/a284da515c3a0620a8225b10655b5e0b

**Comment by yoshuawuyts** [comment]
Update from conversations in chat: we haven't confirmed yet whether this code originates in `async-std` or @serzhiio's application since they also have unsafe atomics code as part of their application.

**Comment by serzhiio** [comment]
Lets close this issue since i rewrote part of my code and problem seems gone.

**Comment by ktmlm** [comment]
> Lets close this issue since i rewrote part of my code and problem seems gone.

This may be caused by two async runtime embed together, see #929
