### ISSUE TITLE
Why is TcpStream::connect no longer using mio::net::TcpStream::connect?

### ISSUE THREAD

**Issue by twittner** [async-rs/async-std#678]
In https://github.com/async-rs/async-std/commit/d25dae54191c8a922410cd2e3ca39e631d28982b, the implementation of `TcpStream::connect` was switched from using mio's non-blocking connect to the blocking `std::net::TcpStream::connect` which is performed in a background thread created by `spawn_blocking`. May I ask why you decided to no longer use mio's non-blocking connect? It seems the background thread spawned is unaware of any future cancellation, e.g. due to timeouts, but continues to run until all SYN retries have been exhausted which may easily last a couple of minutes. This in turn can cause a high number of threads to be created in the background.

**Comment by stjepang** [comment]
Hmmm, that definitely looks like an oversight during the refactor. I agree with you - we should use mio's non-blocking connect. Happy to review a PR for it!
