### ISSUE TITLE
Some typos and improvements for the book

### ISSUE THREAD

**Issue by Lonami** [async-rs/async-std#68]
Collecting a few of them here before making a single commit with all fixes:

* In general, Title Case is not followed consistently for titles.

* [`std::future` and `futures-rs`](https://book.async.rs/overview/std-and-library-futures.html)
  > […] you link those in.. Both uses […]

  There are two periods when there should be either one or three.
* [Stability and SemVer](https://book.async.rs/overview/stability-guarantees.html)
  > […] we introducece functionality […]

  Typo for "introduce".
  > […] in which case we give at least *3 month* of ahead notice.

  This sounds a bit off to me. Maybe "we will give a notice at least 3 months ahead" is better.
* [Futures](https://book.async.rs/concepts/futures.html)
  > […] a very simplified view suffices for us:

  The list that follows starts its items with a lowercase letter. However, the list immediately below starts them with an uppercase letter. This is a bit distracting, and not consistent. Perhaps using a sentence is more appropriated, such as "Computation is a sequence of composable operations which can branch based on a decision, and either run to succession and yield a result, or they can yield an error".
  > […] and how to react on potential events the... well... `Future`

  Probably something like "and how to react on potential events **in** the… well, `Future`" is better.

  I noticed here that code blocks are not syntax-highlighted. Is there a reason for this?
  > When this function is called, it will produce a Future<Output=String>

  That's not the case though, is it? The function is `async fn ... -> Result<String, io::Error>`, not `async fn ... -> String`.
  > *[…] a value available sometime later*

  Should that be "available some time later" or "some later time"?
  > *we will introduce you to `tasks`, which we need to actually *run* Futures

  A bit earlier it was said that calling `poll` repeatedly was enough to drive a future to completion. So is "need" the right word here?
* [Tasks](https://book.async.rs/concepts/tasks.html)
  > Now that we know what Futures are, we now want to run them!

  "Now" is repeated too soon. Maybe "Now that we know what Futures are, we want to run them!" works better.
  > […] task can also has a name and an ID, just like a thread

  Task can also *have* a name.
  > The carry desirable metadata for debugging

  *They* carry.
  > […] task api handles […]

  task *API*.
  > […] mix well with they concurrent execution […]

  with *the* concurrent.
  > `Result<T,E>`

  Missing space after the comma.

**Comment by yoshuawuyts** [comment]
@Lonami hi! Thanks so much for opening this! -- I noticed you never got around to following this up with a PR. Are you still interested in doing so? Is there anything we can do to help?

Thanks heaps!

**Comment by Lonami** [comment]
I did not intend making a PR myself. Rather, I wanted to document a few mistakes, and maybe other people found more. Once we felt they were enough to fix, then anyone could open said PR :)

**Comment by yoshuawuyts** [comment]
@Lonami ah yeah that makes sense -- I'll mark this as "help wanted" then so someone who wants to contribute can pick this up. Thanks heaps!

**Comment by AZanellato** [comment]
Hello! Can I pick this up then? :smile:

**Comment by skade** [comment]
Sure! Looking forward to the patches 🙂.
________________________________
