### ISSUE TITLE
SRV and TXT record lookups

### ISSUE THREAD

**Issue by saghm** [async-rs/async-std#695]
Hello! I'm wondering if there's any standard way in the ecosystem to make DNS queries for SRV and TXT records. I haven't been able to find much in the ecosystem that is able to perform these sort of lookups besides trust-dns, which still seems to be heavily tied to tokio (although there's [an issue open](https://github.com/bluejekyll/trust-dns/issues/926) indicating that this might change in the future). Is there any standard way of doing this right now?

**Comment by yoshuawuyts** [comment]
@saghm that's an excellent suggestion, and would love for something like this to be added to std. Node.js supports this as well, and so does libc.

Probably the best way to make this happen is to create a third-party library that wraps libc/winapi and allows issuing DNS queries. It probably doesn't need to be as elaborate as whatever trust-dns does since it would be a wrapper around OS facilities.

For async-std we would probably not include it, since it's outside the scope of std currently. But we'd be happy to link to it / have it live as part of the org if deemed useful!

Sorry I don't have a better reply for you now; but I hope this is helpful regardless!

**Comment by saghm** [comment]
From rereading what I wrote, I realize I wasn't super clear about what I was asking for; I apologize about that. For context, I work on the [MongoDB driver](https://github.com/mongodb/mongo-rust-driver), and we're in the process of converting the driver to be async. We're hoping to be agnostic to the choice of tokio versus async-std, so for the SRV and TXT lookups we need to do, we can use trust-dns for users who use tokio, but I haven't been able to find any library to help us do this with async-std. Is there anything out there right now that would let us to SRV and TXT lookups with async-std?

**Comment by yoshuawuyts** [comment]
@saghm Unfortunately to my knowledge there currently isn't.

**Comment by yoshuawuyts** [comment]
@saghm I did a bit of research this afternoon, and https://docs.rs/c-ares-resolver/7.0.0/c_ares_resolver/ seems to provide the same resolver Node.js uses, but built on Rust's `std::future`. Perhaps that's a fit!

**Comment by saghm** [comment]
Interesting! We'd probably prefer to use something that isn't wrapping a C/C++ library if possible, but that could be an option.

It looks like `trust-dns` might actually have all the pieces in place for using an arbitrary runtime now; the `AsyncResolver` has a constructor [`from_system_conf`](https://docs.rs/trust-dns-resolver/0.19.3/trust_dns_resolver/struct.AsyncResolver.html#method.from_system_conf) that takes an handle to [`RuntimeProvider`](https://github.com/bluejekyll/trust-dns/blob/master/crates/resolver/src/name_server/connection_provider.rs#L73-L86), which seems like it could be implemented fairly easily for async-std. I imagine it wouldn't be too hard to make a crate that does this, so if it hasn't happened by the time we need it, we might just go ahead and implement that ourselves.

**Comment by saghm** [comment]
To follow up on this, we did end up using `trust-dns`. We haven't abstracted our implementation into a separate crate, but it's fairly small; you can see it [here](https://github.com/mongodb/mongo-rust-driver/blob/6e1feb9be1e8ccf37a18a4dd6f6f2e4a7c6e2302/src/runtime/resolver.rs).

**Comment by dignifiedquire** [comment]
fyi there is now an async-std-resolver in the trust-dns repo: https://github.com/bluejekyll/trust-dns/tree/main/crates/async-std-resolver

**Comment by saghm** [comment]
Oh, awesome!
