### ISSUE TITLE
Zero byte blocks in TCP payload

### ISSUE THREAD

**Issue by Nukesor** [async-rs/async-std#698]
Hi!

First of all, thanks for providing this library. It made async/await finally usable for us!

I'm currently experiencing issues when using `aysnc_std::net::TcpStream` on `localhost`.
Sometimes packets contain zero bytes, even if the Sender hasn't finished sending yet.

I recreated this scenario with a byte vector of 100k `a` chars and it fails very consistently.
The receiving side always receives 100k bytes, but some packets seem to be incomplete and instead filled with zero-bytes.
It must also be to mentioned, that this doesn't fail deterministically.

```
Found zero block in payload
Position: 11017, Size: 983, End: 12000
Found zero block in payload
Position: 77483, Size: 517, End: 78000
```
Packet size is 1500 bytes.

The minimal example repository with some debug output can be found here:
https://github.com/Nukesor/debug

One thing that caught my eye was, that the errors tend to pop up more often, if other programs open and use tcp connections (Opening a browser and going to reddit tends to increase the probability to get an error.)

I suspect some kind of OS-specific TCP buffer problem. However this is still somewhat strange, since I would expect some kind of error message or failure.

If I can provide any further information, I'ld be happy to help.

Failing Rust Versions:
- Nightly 1.42.0
- Stable 1.41.0

**Comment by Matthias247** [comment]
1. `TcpStream::read` will read up to a maximum amount of bytes - but can return as soon as it has read any byte. The amount of bytes which are actually read are returned. But you ignore the result [here](https://github.com/Nukesor/debug/blob/master/src/main.rs#L94). Therefore you are not reading as many bytes as you think and get `0` initialized bytes in your result. Using a `read_all` API should fix your code.
2. TCP is a byte stream. not a channel of messages. If you do something along
    ```rust
    let mut iter = payload.chunks(1500);
    while let Some(chunk) = iter.next() {
       socket.write_all(chunk).await?;
    }
    ```
   don't expect the receiver to read also "frames" of 1500 bytes. There are no frames on TCP. You just    pump bytes into a Stream, and the receiver reads them. The transmission layer has the freedom to fragment you bytes into as many packets or buffers as necessary. The peer could read `100_000` 1-byte elements. If you need any framing, you have to do it on application level.

**Comment by Nukesor** [comment]
Thanks a lot for the detailed explanation!

Looks like I missed something substantial when learning about TCP back then. I'll try to fix the implementation as you suggested.

Thanks again for clarifying!

However, the Result didn't return an Error
