### ISSUE TITLE
"capacity must be positive" error when sending between tasks

### ISSUE THREAD

**Issue by Licenser** [async-rs/async-std#712]
I'm hitting a `capacity must be positive` error when sending between two tasks and I'm a bit unsure what could cause this I think it's a condition that should never be hit?

**Comment by Licenser** [comment]
After re-reading the code it seems to be caused by creating a channel with 0 elements. Is `channel(0)` is something that is supposed to work?

**Comment by genone-colton** [comment]
This is documented behavior. See https://docs.rs/async-std/1.5.0/async_std/sync/fn.channel.html

**Comment by yoshuawuyts** [comment]
`channel(0)` is indeed not supposed to work.
