### ISSUE TITLE
Update mio to v0.7

### ISSUE THREAD

**Issue by leaxoy** [async-rs/async-std#717]
Mio v0.7 has been released, we should update it.

**Comment by k-nasa** [comment]
Thx!

There are major changes where are currently using mio.
https://github.com/async-rs/async-std/pull/631

Once this PR has been finalized, I will work on this update.

**Comment by vertexclique** [comment]
Related to https://github.com/async-rs/async-std/issues/699

**Comment by leaxoy** [comment]
@k-nasa  great jobs, I can't wait #631 merged.

**Comment by k-nasa** [comment]
@leaxoy  Listening late, what motivates async-std to upgrade mio version?

**Comment by dignifiedquire** [comment]
Because 0.6 is unlikely to be maintained, and we want to make sure we use maintained up to date dependencies.

**Comment by dignifiedquire** [comment]
I have a branch that compiles, but some tests hang, so this needs more work: https://github.com/async-rs/async-std/tree/mio-0-7

**Comment by stjepang** [comment]
This can be closed because async-std is not using mio anymore.
