### ISSUE TITLE
How to set TCP SO_KEEPALIVE?

### ISSUE THREAD

**Issue by Ryan-Git** [async-rs/async-std#718]

**Comment by yoshuawuyts** [comment]
Construct a socket using [`socket2`](https://docs.rs/socket2/0.3.11/socket2/struct.Socket.html#method.set_keepalive) and then convert it into a `std::net::TcpListener` and then convert *that* into an `async_std::net::TcpListener`. Alternatively [`net2::TcpStreamExt`](https://docs.rs/net2/0.2.33/net2/trait.TcpStreamExt.html#tymethod.keepalive) provides a similar method as well

The right solution here would be if we had this method exposed directly on `std::net::TcpStream`, as it's fairly common to want to set this.

**Comment by Ryan-Git** [comment]
thanks. Agree with adding it to std. For now I'm OK with socket2..
