### ISSUE TITLE
Considering exporting WakerSet as pub - now is pub(crate)

### ISSUE THREAD

**Issue by Mallets** [async-rs/async-std#728]
Hi! I'm building a quite complex application around async-std library and in some cases I'm writing my own futures. The `WakerSet` defined in `async-std/sync/` seems to be a very handy structure to have when writing futures. Unfortunately, it is currently exported as `pub(crate)` and not as `pub` leading to the fact that I can not import it in my own application.

Is there any reason that prevents the `WakerSet` to be `pub`? From the current status it seems that it could be made public with no issues, but perhaps I'm missing something...

Thanks!
Luca

**Comment by yankuu** [comment]
I would also love to use `WakerSet`. I believe the current plan (see #549) is to put it in [async-utils](https://github.com/async-rs/async-utils), which is still a placeholder today.

**Comment by Mallets** [comment]
Great, looking forward to have it in async-utils then!

**Comment by Mallets** [comment]
I'm closing this issue since an alternative plan seems to be already in place  (see [#549 ](https://github.com/async-rs/async-std/issues/549)).

**Comment by Mallets** [comment]
I'm closing this issue since an alternative plan seems to be already in place (see [#549 ]).
