### ISSUE TITLE
Derive Async

### ISSUE THREAD

**Issue by bedax** [async-rs/async-std#737]
An unfortunate consequence of async in Rust is that it has split the ecosystem. Library developers have to make a decision early on: sync or async. Once that decision has been made, the other side of the community is shunned, generally unable to use the library, especially if `block_on` doesn't support the target platform (wasm?). Some particularly diplomatic developers may decide to develop essentially two libraries, a sync one and an async one, but that isn't an appealing option to most.

It seems to me a macro could be developed:

```rust
#[optional_async]
fn read_config() -> std::io::Result<String> {
   let f = std::fs::File::open("config.ini")?;
   ...
}
```

Which would translate to:

```rust
#[cfg(feature="async")]
async fn read_config() -> async_std::io::Result<Config> {
   let f = async_std::fs::File::open("config.ini")?;
   ...
}

#[cfg(not(feature="async"))]
fn read_config() -> std::io::Result<Config> {
   let f = std::fs::File::open("config.ini")?;
   ...
}
```

And then the library user can enable the async feature if required, and the overhead of supporting async would be greatly reduced.

My procedural macro skills are not the best though, so I'm not sure if this is possible, hence the post. Any thoughts? One problem that I can see is that if the macro comes across a type like `io::Result` instead of `std::io::Result`, it would be hard for the macro to know that the referenced type is from the standard library and has an equivalent in async_std.

I'm happy to give this a go if no one else more qualified is interested, and if others agree this is a good solution to the problem.

**Comment by skade** [comment]
While I see this as an interesting idea, it only works in a number of very narrow cases where there's an exact parity between the async and the sync cases. This is not always the case. I would even go as far as believing that _in general_, async interfaces look a little different from sync interfaces.

Also, the feature flag has an issue in the sense that it's "one or the other".

In general, I think it is an interesting idea to be explored, but not within async-std. This should be separate library, for potential adoption into the async.rs umbrella if it works well.
