### ISSUE TITLE
too slow

### ISSUE THREAD

**Issue by baic009** [async-rs/async-std#745]
use async_std::task;

fn main() -> Result<(), std::io::Error> {
    let pid = std::process::id().to_string();
    std::fs::write(".pid", &pid).expect("Unable to write file");
    println!("Master {} is running", pid);

    task::block_on(async {
        let mut app = tide::new();
        app.at("/").get(|_| async move {
            let s = std::thread::current();
            println!("{:?} is running", s.id());
            let t = std::time::Duration::from_secs(1);
            std::thread::sleep(t);
            "Hello, world!"
        });

        app.listen("127.0.0.1:3000").await?;
        Ok(())
    })
}
// ab -c 3000 -n 30000 http://localhost:3000/

**Comment by skade** [comment]
`std::thread::sleep` is not intended to be used in async-std as it blocks the executor thread. use `async_std::task::sleep`
