### ISSUE TITLE
Joining futures

### ISSUE THREAD

**Issue by CarlosLanderas** [async-rs/async-std#75]
Hello, sorry for the ignorance, but I would like to know if this crate has available some 
macro / mechanism to join futures so they can ran concurrently like futures crate has.

```
#![feature(pin, async_await, futures_api)]
use async_std::io;
use async_std::task;
use serde_derive::Deserialize;

#[macro_use]
extern crate futures;

#[derive(Deserialize, Debug)]
struct Post {
    #[serde(rename = "userId")]
    user_id : usize,
    id: usize,
    title: String,
    completed: bool
}

fn main() {
    task::block_on(async {
        let post_fut  = surf::get("https://jsonplaceholder.typicode.com/todos/1").recv_json::<Post>();
        let post2_fut = surf::get("https://jsonplaceholder.typicode.com/todos/2").recv_json::<Post>();
        let (result1, result2 ) = join!(post_fut, post2_fut);
        println!("{:?}", result1.unwrap());
        println!("{:?}", result2.unwrap());
    });
}

```

**Comment by skade** [comment]
Hi, we recommend using the futures crate for that, currently.

For our current discussion on adding `join` and `select`, see https://github.com/async-rs/async-std/issues/14. Short summary: we're not sure of what currently exists is stable enough or if we can find our own useful design.

**Comment by CarlosLanderas** [comment]
Thanks @skade, I'll follow the discussion.

**Comment by skade** [comment]
You're welcome :).
