### ISSUE TITLE
is using `task::spawn_blocking` for cpu bound tasks adviced?

### ISSUE THREAD

**Issue by jannickj** [async-rs/async-std#752]
The documentation says it will be given its own thread from a special threadpool, and that it's designed for long running blocking code. Is there any reason why we can't use this for CPU heavy tasks or is there something that might make this a bad idea?

**Comment by jimblandy** [comment]
Yes, if you have a CPU-bound task, or any sort of task where polling its future may take a long time, that's the case `spawn_blocking` is intended to solve.

However, there's a bit of uncertainty around this. The [async-std blog](https://async.rs/blog/stop-worrying-about-blocking-the-new-async-std-runtime/) had an article talking about how you can just use `spawn` for everything, and the runtime will dynamically detect if it blocks for a long time, and let it have that thread for its exclusive use. But I'm [told](https://github.com/async-rs/async-std/pull/906#issuecomment-721589009) that that strategy may be on hold.
