### ISSUE TITLE
File.write sometimes writes incomplete bytes

### ISSUE THREAD

**Issue by grenierdev** [async-rs/async-std#761]
```
rustc 1.43.0 (4fb7144ed 2020-04-20)
cargo 1.43.0 (3532cf738 2020-03-17)
rustup 1.21.1 (7832b2ebe 2019-12-20)
toolchain stable-x86_64-pc-windows-msvc
os Windows 10 Pro 1909 18363.778
async-std 1.5.0
```
[Minimal repo to reproduce issue](https://github.com/grenierdev/async-std-issue), run `cargo test` to reproduce the issue.

The problem does not happen when using `std::fs` and `std::io`.

It might be just some dumb error I made since I'm fairly new to Rust and async-std but when I write a sequence of `u32` to a file after a few bytes, the bytes written are less than 4 bytes. When written to a memory using the Cursor, everything is fine.

Same issue under Windows Subsystem for Linux using the `stable-x86_64-unknown-linux-gnu` toolchain.

**Comment by grenierdev** [comment]
It seems like if I write `N` bytes (where `N < 8`) before the for loop, the first write in the loop will be trimmed to `8-N` bytes.

The minimal repo writes 5 bytes (`WORD0`) and then 3 bytes of the first `u32`. All the subsequent iteration writes 4 bytes correctly.

If we change the first `WORD0` to `LETTERS` (7 bytes), only 1 byte of the first `u32` gets written.

**Comment by dignifiedquire** [comment]
you need to use `write_all` I believe, or check that the value returned from `write` is actually the length of the value you are trying to write

From the docs of `write`:
> Writes some bytes into the byte stream.
> Returns the number of bytes written from the start of the buffer.

From the docs of `write_all`:
> Writes an entire buffer into the byte stream.
> This method will continuously call write until there is no more data to be written or an error is returned. This method will not return until the entire buffer has been successfully written or such an error occurs.

**Comment by grenierdev** [comment]
@dignifiedquire Thank you to have taken the time to point me in the right direction. `write_all` did solve my issue.
