### ISSUE TITLE
async-std@1.6.0-beta.1: cannot run an executor inside another executor 

### ISSUE THREAD

**Issue by GopherJ** [async-rs/async-std#766]
after upgrading to 1.6.0-beta.1, I start to get this error message. Previous version: 1.5.0

**Comment by dignifiedquire** [comment]
This sounds like you are running `block_on` inside another `block_on`, which was not really well supported before, but is now being detected and not ignored anymore.

**Comment by GopherJ** [comment]
@dignifiedquire  I removed `block_on` inside block on but all my tests still fail, could you please help having a look, I would like to test the new version because maybe wasm compiles.

https://github.com/GopherJ/casbin-rs/tree/upgrade-async-std

**Comment by GopherJ** [comment]
Also this error is a runtime error which makes it harder to identify during compile time, is it possible to locate it during compile time?

**Comment by andysalerno** [comment]
I'm receiving the same error.  At first it was throwing from a `block_on`, so I removed the `block_on` and have none remaining in the codebase.

From inspecting the trace, it looks like there's a `block_on` in async-std-1.6.0-beta.1/src/fs/file.rs:318.

In my code, the `File` is going out of scope, I guess invoking the `drop()` of the `File`, which leads to a stack trace like this, which I guess involves a block-in-a-block (since my `main()` is decorated with the `async_std::main` attribute):

```
  21: async_std::task::block_on::block_on
             at /home/andy/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.0-beta.1/src/task/block_on.rs:33
  22: <async_std::fs::file::File as core::ops::drop::Drop>::drop
             at /home/andy/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.0-beta.1/src/fs/file.rs:318
  23: core::ptr::drop_in_place
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libcore/ptr/mod.rs:177
  24: core::ptr::drop_in_place
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libcore/ptr/mod.rs:177
  25: toygrep::buffer::async_line_buffer::AsyncLineBufferReader<R>::take_line_buffer

```

https://github.com/async-rs/async-std/blob/master/src/fs/file.rs#L318

**Comment by andysalerno** [comment]
Did a quick test, this is failing:
```rust
#[async_std::main]
async fn main() {
    async_std::task::block_on(async move {
        println!("Hello, world!");
    });
}
```
Which makes sense if we are saying that nested `block_on`s are not allowed (and assuming the impl for the `async_std::main` attribute is using `block_on` somehow).

But this is not failing:
```rust
fn main() {
    async_std::task::block_on(async move {
        let f = async_std::fs::File::open("test.txt").await;
        drop(f);
    });
}
```

Even though `File::drop()` invokes `block_on()`?  Which clearly results in a nested `block_on()`?  Maybe I'm missing something... the callstack I pasted in my above comment definitely shows an issue coming from `async_std::fs::File::drop()`.

**Comment by dignifiedquire** [comment]
Thank you @andysalerno for the test and report. #768 fixes the case for `File` dropping.
