### ISSUE TITLE
Implement `io::Read` and `io::Write` for X

### ISSUE THREAD

**Issue by xpepermint** [async-rs/async-std#769]
It looks like the structs that I need to implement the Read/Write traits are private.

```rs
impl io::Read for Stream {
    fn read(
        &mut self,
        buf: &mut [u8],
    ) -> impl Future<Output = io::Result<usize>> + [ReadFuture<Self>] // ReadFuture is private!
    where
        Self: Unpin
    {
        match self {
            Stream::Inet(s) => (&mut (&*s)).read(buf),
            #[cfg(unix)]
            Stream::Unix(s) => (&mut (&*s)).read(buf),
        }
    }
    ...
}
```

How can I do that?

**Comment by dignifiedquire** [comment]
You need to implement poll_read not read to implement the async version of Read. In which you cam delegate to the poll_read methods of your underlying streams

**Comment by xpepermint** [comment]
Ow, right! Thanks.

**Comment by xpepermint** [comment]
@dignifiedquire could you please just give me a hint for delegation? If you call `stream.read()` how to get to the `poll` method?
