### ISSUE TITLE
Build link-checking for book

### ISSUE THREAD

**Issue by skade** [async-rs/async-std#77]
Land https://github.com/async-rs/async-std/pull/61 and make sure it doesn't break netlify ;).

* Turn book building into a script
* Make sure link checking only triggers during testing
* On deploy environments, download the mdbook and linkcheck binary

**Comment by yoshuawuyts** [comment]
@skade can this be closed?

**Comment by yoshuawuyts** [comment]
Ah, actually going to close this as a duplicate of https://github.com/async-rs/async-std/issues/82 -- even though it's filed later it seems to still be active.
