### ISSUE TITLE
async-std not available on play.rust-lang.org

### ISSUE THREAD

**Issue by xpepermint** [async-rs/async-std#784]
It seems that `async_std` is not available in the Rust playground at https://play.rust-lang.org/. This makes difficult for admins to provide complete answers to questions. Can we somehow add support it?

**Comment by taiki-e** [comment]
https://play.rust-lang.org/help#features-crates

> The playground provides the top 100 most downloaded crates from crates.io, the crates from the Rust Cookbook, and all of their dependencies.

**Comment by dignifiedquire** [comment]
This is unfortunate, but there is nothing we can do about it, other than get more people to download async-std :D
