### ISSUE TITLE
async-std@1.6.0-beta.1: thread 'async-std/runtime' panicked at 'cannot convert a blocking task into `JoinHandle`'

### ISSUE THREAD

**Issue by Keruspe** [async-rs/async-std#787]
Running `task::spawn_blocking(move || { /* insert here a blocking task */ }).await` leads to

`thread 'async-std/runtime' panicked at 'cannot convert a blocking task into `JoinHandle`', <::std::macros::panic macros>:2:4`

Not sure how to gather more information

**Comment by Keruspe** [comment]
@stjepang seems to be caused by https://github.com/stjepang/smol/commit/ce315f3d9a144d5a5db319c5290d3117201a5fab

**Comment by Keruspe** [comment]
I confirm that downgrading smol from 0.1.6 to 0.1.7 solves the issue. Not sure if it needs something on the smol side or if async-std needs to be updated to the new smol behaviour

**Comment by stjepang** [comment]
I've reverted some recent changes in smol and published a new version. `cargo updae` should fix the problem. Sorry about that!

**Comment by dignifiedquire** [comment]
This was a regression in smol, which is now fixed if you run `cargo update`
