### ISSUE TITLE
Various failing tests on master, yet green on CI

### ISSUE THREAD

**Issue by seirdb** [async-rs/async-std#788]
If I run `cargo test —all —features “unstable attributes”` on the latest master (2b6c7fe) I get 7 failing tests. Yet on CI they seem to have passed.

CI run: [OK](https://github.com/async-rs/async-std/actions/runs/103756272).

Failing tests:

```
failures:
    src/io/copy.rs - io::copy::copy (line 122)
    src/macros.rs - eprint (line 113)
    src/macros.rs - eprintln (line 147)
    src/macros.rs - print (line 23)
    src/macros.rs - println (line 73)
    src/net/addr.rs - net::addr::ToSocketAddrs (line 35)
    src/task/spawn_blocking.rs - task::spawn_blocking::spawn_blocking (line 18)
test result: FAILED. 383 passed; 7 failed; 3 ignored; 0 measured; 0 filtered out
```

Run on ubuntu with rustc version 1.43.1.

**Comment by seirdb** [comment]
I’ve only listed the doc-tests apparently, the full list is:

```
test fs::file::tests::async_file_drop ... FAILED
test to_socket_addr_str_bad ... FAILED
test to_socket_addr_str_u16 ... FAILED
test to_socket_addr_str ... FAILED
test io_timeout_timedout ... FAILED
test open_file ... FAILED
test resolve_address ... FAILED
test src/io/copy.rs - io::copy::copy (line 122) ... FAILED
test src/macros.rs - eprint (line 113) ... FAILED
test src/macros.rs - eprintln (line 147) ... FAILED
test src/macros.rs - print (line 23) ... FAILED
test src/macros.rs - println (line 73) ... FAILED
test src/net/addr.rs - net::addr::ToSocketAddrs (line 35) ... FAILED
test src/task/spawn_blocking.rs - task::spawn_blocking::spawn_blocking (line 18) ... FAILED
```

**Comment by dignifiedquire** [comment]
you need to pass the correct feature flags, take a look at what the CI passes for them

**Comment by seirdb** [comment]
> you need to pass the correct feature flags, take a look at what the CI passes for them

Looking at ci.yml:93, it says `args: --all --features "unstable attributes"`, which is what I’ve run
> If I run cargo test —all —features “unstable attributes” on the latest master ...

**Comment by seirdb** [comment]
By the way, I came across this when looking at issue #785. The panic seen there is also seen in the failing tests for `io_timeout_timedout`.

The panic that’s being catched there is the same and different from what the test asserts. So that test is indeed broken, yet green on CI.

**Comment by seirdb** [comment]
I made some progress. I did find a difference between the CI environment and my setup: the number of threads available to spawn a runtime.

I assume the CI only has 1 thread. If I change the number of threads spawned to just **1** in `./src/rt/mod.rs` then all is green.

So there seems to be a problem introduced with the `smol` backend.

**Comment by seirdb** [comment]
Scrap that last comment. I did a `cargo clean` and a new `cargo build`.

It seems that the `smol` crate has been updated to `0.1.8` in between builds and that seemed to fix these issues.
