### ISSUE TITLE
Configure thread pool

### ISSUE THREAD

**Issue by LukeMauldin** [async-rs/async-std#813]
Is there a way to configure the thread pool for `async-std`?  In particular, I have some web applications where I would like to set the number of worker threads to the number of CPUs on the machine.  However, I have some Rust command line applications that primarily call C/C++ functions that may use thread local storage where I only one want "main operating thread".  In tokio I can configure this via a builder with `core_threads` (https://docs.rs/tokio/0.2.21/tokio/runtime/struct.Builder.html) and/or using `basic_scheduler` or `runtime_scheduler`.  How can I achieve this with async-std?

**Comment by yoshuawuyts** [comment]
Hi @LukeMauldin, thanks for asking! We allow `async-std` to be configured through env vars: https://docs.rs/async-std/1.6.0/async_std/#runtime-configuration. Hope this is helpful!

**Comment by LukeMauldin** [comment]
Just to clarify, if I set `ASYNC_STD_THREAD_COUNT` to 1 then that means all work will be performed on one OS thread similar to the C/C++ threading model?
