### ISSUE TITLE
Add BufWriter

### ISSUE THREAD

**Issue by LeshaInc** [async-rs/async-std#83]
There is already a `BufReader`, so people would expect to have a `BufWriter` too. A lazy implementation is to simply wrap `BufWriter` from `futures-0.3`.

**Comment by Drevoed** [comment]
I am currently trying to implement this and encountered some issues, if I make a pull request will someone be able to guide me through?

**Comment by skade** [comment]
Hi @Drevoed, yes, we're happy to mentor there. Please be aware that we're currently en route to RustConf, so we might take some time.

Also feel free to jump on the Discord.

**Comment by yoshuawuyts** [comment]
Ref #131 also (tracking issue for `async_std::io`)
