### ISSUE TITLE
Consider `future.spawned()` syntax

### ISSUE THREAD

**Issue by jerry73204** [async-rs/async-std#831]
I proposed the same idea to tokio-rs/tokio#2652. I'm glad if async-std could have it.

**Comment by yoshuawuyts** [comment]
Hi, thanks for opening this! Following @taiki-e's comment in https://github.com/tokio-rs/tokio/issues/2652 I'm not quite sure what the benefits would be for integrating this into `async-std`. If Tokio decides to adopt a variant of this it'd be interesting to see how it would work out, but for the time being I don't think we can take on more surface area for spawning tasks beyond what we already expose. Thanks!
