### ISSUE TITLE
Problem reading / writing in TCP stream.

### ISSUE THREAD

**Issue by MoMannn** [async-rs/async-std#835]
I am playing with http2 and wanted to make a simple server to test it out. 

I created a TCP server and am reading and parsing http2 bytes which works without a problem. 
But then I tried to write response frames while reading TCP stream this resulted in me then reading the frames I written. Basically I cannot read and write into the TCP stream at the same time. 

I created a simple example code of this that you can try out that simulates the above problem:
https://github.com/MoMannn/rust-async-std-server-issue-example

**Comment by stjepang** [comment]
I'm not familiar with http2 but this doesn't seem to be an issue with async-std to me because even a blocking version with `std` networking exhibits the same behavior:

https://gist.github.com/stjepang/aa46961abea8010d1f71b5933ad9ba1f

**Comment by MoMannn** [comment]
🤔 Closing this issue here. Was sure this had to do something with async. Thanks for quick response.
