### ISSUE TITLE
Stream::merge may block indefinitely

### ISSUE THREAD

**Issue by Licenser** [async-rs/async-std#841]
The [pull in order function](https://github.com/async-rs/async-std/blob/c82b1efb692751588bc3600d3def78166d707fb5/src/stream/stream/merge.rs#L56
) has the potential to block indefinitely. When it translates a `Poll::Ready(None)` into a `Poll::Pending` it doesn't call the waker.

from the rust docs:
> When a function returns Pending, the function must also ensure that the current task is scheduled to be awoken when progress can be made.

The function is called with a random order makes it unlikely but not impossible to happen.

Rewriting it the following way would assure correct handling:

```rust
fn poll_next_in_order<F, S, I>(
    first: Pin<&mut F>,
    second: Pin<&mut S>,
    cx: &mut Context<'_>,
) -> Poll<Option<I>>
where
    F: Stream<Item = I>,
    S: Stream<Item = I>,
{
    match first.poll_next(cx) {
        Poll::Ready(None) => second.poll_next(cx),
        Poll::Ready(item) => Poll::Ready(item),
        Poll::Pending => match second.poll_next(cx) {
            Poll::Ready(None) => {
                cx.waker().wake_by_ref();
                Poll::Pending
            }
            Poll::Pending => Poll::Pending,
            Poll::Ready(item) => Poll::Ready(item),
        },
    }
}


```

**Comment by yoshuawuyts** [comment]
@Licenser thanks for reporting! I think you're indeed correct about the problem, but I'm wondering if perhaps we would change the solution somewhat. What I'm afraid of about the solution that you're proposing is that in the case the second stream finishes before the first stream, we indefinitely keep re-scheduling the stream on the executor.

Instead I would propose we effectively "fuse" the streams, so if one has returned `None` once, we no longer ask them for more items.

**Comment by yoshuawuyts** [comment]
@Licenser Actually on a second read I don't think there actually is a bug here!

In order for the second future to return `Poll::Ready(None) => Poll::Pending`, the first future must have returned `Poll::Pending`. This means there's a `Waker` available inside the first future which is responsible for the stream to make progress. After all: otherwise the first future wouldn't have returned `Poll::Pending`.

Yay, no bug!

**Comment by Licenser** [comment]
That makes sense, but with the randomness removed (i.e. always taking the same order) I had to add the weaker so it won't block but it might have been a side effect?.

**Comment by Licenser** [comment]
Seems the non-waking poll was down the chain - you were right Yoshua, sorry about mislabeling it as a bug here :)
