### ISSUE TITLE
Panics on Windows Vista

### ISSUE THREAD

**Issue by WeaponMan** [async-rs/async-std#844]
Async-std panics with "rwlocks not available" on Windows Vista.
I migrated from tokio that runned fine (expect the random hang on all windows after dropping connection)

**Comment by stjepang** [comment]
I believe that comes from wepoll, which uses RW locks in its implementation:

https://github.com/piscisaureus/wepoll/blob/0598a791bf9cbbf480793d778930fc635b044980/wepoll.c#L525

I feel surprised that Vista is still being used so I'm inclined to close this - and Vista has been an unsupported OS for several years now. But if I may ask, are you planning to upgrade to a newer version of Windows? I guess I'm trying to see if this is an important issue to you or a minor annoyance nudging you to upgrade?

**Comment by WeaponMan** [comment]
Its old server "Windows SBS 2008" (same as Vista) they dont really wanna upgrade that.

**Comment by WeaponMan** [comment]
And RWLocks are partially supported on Vista only this function that panic comes in Win 7.

https://docs.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-tryacquiresrwlockexclusive

**Comment by WeaponMan** [comment]
Ok, patched that up myself in smol. https://github.com/WeaponMan/smol/commit/1bf6f375f47e489b0bfc0d06e4a4131b7decfb6d
I hope the new version with the new scheduler wont be with `std::sync::Mutex:try_lock` function.
