### ISSUE TITLE
Prioritized Merge

### ISSUE THREAD

**Issue by Licenser** [async-rs/async-std#847]
Hi I needed a version of `Merge` that prioritized one stream over another and made an implementation of that based on `Merge` would there be interest for a PR to add this?
The behavior is that it will always prioritize the first stream and only consume the secondary when the first one isn't ready to be read. This can lead to the second stream never being consumed but that's intentional.

If added would a `stream.prioritize_over(other_stream)` function analogous to `stream.merge(other_stream)` make sense?

**Comment by yoshuawuyts** [comment]
@Licenser Can you share more about what you need this functionality for? So far it sounds fairly specialized; somewhere between `Stream::chain` and `Stream::merge`. I would like to understand better what the rationale behind it is before we consider it for inclusion.

**Comment by Licenser** [comment]
Absolutely! I'll link the RFC relating to it on tremor at the end and try to summarize it in a simplified version.

we got a system that has 3 components, sources, pipelines and sinks. a source generates/reads data, sends it over a channel to a pipeline, that does some computations on it then sends it over a channel to a sink. Now the sink may or may not create some acknowledgments for that data, send it those through another channel to the pipeline which again does something with it, then sends it back, over a channel, to the source.

To the forward flow source -> pipeline -> sink uses bounded channels.

the contra flow sink -> pipeline -> source uses unbounded channels.

Since we know that contraflow always relates to forward flow in a 1:N relation (where N might be 0) the unboundedness of the contraflow channels prevents live-locks but, and here is where the prioritized merge comes into play, to prevent the unbounded channels to become actually unbounded (not bounded by the N) we prioritize reading them.

So:
* A source only generates/reads new data if no contraflow messages are pending for it.
* A pipeline only processes a new forward-message if no contraflow messages are present.

Using `Stream::chain` would mean, if I understand the documentation correctly, that the contraflow would need to be completely closed for the forward flow to be processed - which isn't the case for us.

Using `Stream::merge` would make it unpredictable when contraflow is processed and might lead to the unbounded channel to become truly unbounded - which while unlikely, is really a possible bug I'd not want to have to debug in production :joy:.

The prioritized merge allows us to always process forward flow unless there is contraflow :).

If it's to specialized to include, that's totally fine I understand that :D. it's simple enough to implement if someone needs it, I just figured it is already written and might be useful so why not give back some oss-love.

[rfc](https://github.com/wayfair-tremor/tremor-rfcs/pull/18/files#diff-db9b48f6159ef8099d1eeec4c35fb645R44-R50)

**Comment by yoshuawuyts** [comment]
> Using Stream::merge would make it unpredictable when contraflow is processed and might lead to the unbounded channel to become truly unbounded

> [from the rfc] To elaborate, we look at the source as an example. The loop of communication creates the possibility that the source sends an event to the pipeline, blocking at a full queue. At the same time, the pipeline sends an insight to the source, also blocking at a full queue and thus locking forever.

If I understand this correctly you have a system that can generate messages that it itself ingests again. But you want to prioritize messages generated by other systems in all cases. You're using an unbounded queue to store the messages generated from within the system, and a bounded queue for messages generated from outside the system.

If I'm reading this correctly then under pressure the system will always prioritize external messages, and is intended to stop parsing internal messages. This seems like it could cause memory to overflow? Which I believe is the exact problem you were trying to mitigate? -- I feel like I may be missing something.

Either way, related to `async-std`, this seems like a fairly specific adapter that at least for now may be too precise to include. But it's something interesting to keep in mind, because this can indeed not be expressed with existing patterns as it is.

**Comment by Licenser** [comment]
> If I'm reading this correctly then under pressure the system will always prioritize external messages, and is intended to stop parsing internal messages. This seems like it could cause memory to overflow? Which I believe is the exact problem you were trying to mitigate? -- I feel like I may be missing something.

The other way around, we're prioritizing internal messages (which are only ever triggered by external messages) over external messages to prevent that memory overflow problem :).

But yes makes sense that that is too specific for async-std :+1:
