### ISSUE TITLE
[docs] [typo] Small typo in async_std::stream docs

### ISSUE THREAD

**Issue by leklachu** [async-rs/async-std#860]
Just a small typo in the docs for stream,

> Streams do not have to be finite. As an example, **an repeat** stream is an infinite stream

https://docs.rs/async-std/1.6.3/async_std/stream/index.html#infinity

Looks like it's autoconversion from std::iter
https://doc.rust-lang.org/std/iter/index.html#infinity

**Comment by surechen** [comment]
Hello, I noticed this problem when browsing the issues and I agree with your opinion. I think I can submit a PR to fix this problem.

**Comment by Fishrock123** [comment]
Fixed by https://github.com/async-rs/async-std/pull/926
