### ISSUE TITLE
CI check for wasm isn't working

### ISSUE THREAD

**Issue by tomaka** [async-rs/async-std#861]
Building async-std for the wasm target is completely broken at the moment:

- https://github.com/async-rs/async-std/issues/851
- https://github.com/async-rs/async-std/issues/843

The reason why it hasn't been detected is that the CI of async-std for wasm isn't working. [Here](https://github.com/async-rs/async-std/runs/1003328709#step:9:1)'s an example.

**Comment by jbr** [comment]
https://github.com/async-rs/async-std/pull/852 addresses the CI issue
