### ISSUE TITLE
Please don't pull in wasm dependencies (via gloo-timers) on non-wasm platforms

### ISSUE THREAD

**Issue by joshtriplett** [async-rs/async-std#865]
async-std with the `unstable` feature enabled pulls in various wasm-specific dependencies via the `gloo-timers` dependency of `futures-timer`, even on non-wasm platforms. This adds quite a few dependencies, and shows up when building `tide`.

**Comment by yoshuawuyts** [comment]
@joshtriplett agreed; we should fix that.

**Comment by e00E** [comment]
When I looked into this I was confused as to why this happens because in Cargo.toml it looks like it shouldn't be the case. I think it is related to https://github.com/rust-lang/cargo/issues/1197 .

**Comment by jbr** [comment]
Possible fix at https://github.com/async-rs/async-std/pull/864 doesn't rely on target-specific features and switches to a `wasm` feature, which would be semver-major for wasm users.

As far as I can tell, this issue also ends up interfering with the `alloc` feature

**Comment by Fishrock123** [comment]
See also this older duplicate issue: https://github.com/async-rs/async-std/issues/823

**Comment by dignifiedquire** [comment]
fixed on master

**Comment by K4rakara** [comment]
`gloo-timers` is still enabled by default, thus pulling in all of the wasm dependencies unless you go out of your way to use `default-features = false` and all the other features manually.
