### ISSUE TITLE
[Question] How to use a-chat?

### ISSUE THREAD

**Issue by TENX-S** [async-rs/async-std#876]
OS: macOS 10.15.6
Rust: rustc 1.48.0-nightly (d006f5734 2020-08-28)
Terminal: iTerm2

I used this example in the following way, but its behavior was not what I expected.

In the first tab of terminal,  run server:

```shell
$ cargo run --release --example a-chat server
```

In the second one, run client:
```shell
$ cargo run --release --example a-chat client
```

Same for the third one.

Then, the server end showed two messages:
```shell
Accepting from: 127.0.0.1:52987
Accepting from: 127.0.0.1:52988
``` 

When I type a message in the second tab or the third one, like "Hi, there", the server end doesn't show my message.

How can I run this example properly, like a normal chat tool?

**Comment by Implocell** [comment]
??
