### ISSUE TITLE
Sender::send polls forever if channel is disconnected. 

### ISSUE THREAD

**Issue by maffoo** [async-rs/async-std#880]
`Receiver::recv` fails with a `RecvError` if the channel is disconnected, but `Sender::send` will just spin forever in that case with a future that is always pending. I'd like to have a send method that keeps trying if the channel is full but fails with a `SendError` if the channel disconnects. This could be a new method, something like `Sender::send_if_connected`.

**Comment by maffoo** [comment]
Instead of adding a new method (or perhaps in addition) it might be nice to change the behavior of the existing `send` method to finish immediately and drop messages if the channel is disconnected. It is already the case that messages could be added to the channel buffer and then dropped when the channel is disconnected, so `send` completing is no guarantee that messages will be received.

**Comment by yoshuawuyts** [comment]
I think this is closed by #827 which adds a new channel impl.

**Comment by Fishrock123** [comment]
(Closing, we can re-open if it isn't.)
