### ISSUE TITLE
v1.6.4 (regression) `not currently running on the Tokio runtime.` crash

### ISSUE THREAD

**Issue by sync** [async-rs/async-std#881]
When using the latest async std version:
`async-std = { version = "1.6.4", features = ["attributes", "tokio02"] }` and `tokio02`

I get an error message deep down saying `not currently running on the Tokio runtime`.

I rely on the `tokio02` feature so I can keep using `https://crates.io/crates/cloud-pubsub` that has a dependency on the Tokio runtime. 

If I use 1.6.3 instead, I don't get the error
`async-std = { version = "=1.6.3", features = ["attributes", "tokio02"] }`

I looked at the latest release note and I see nothing related to a potential `tokio02` change that might explain why I now get this crash. 

I'll attach a sentry crash report and happy to provide further details if necessary

**Comment by sync** [comment]
Here is the symbolicated crash report from sentry:

[3ddcff0bcff64b8f8769056c7fa684e2-symbolicated.crash.zip](https://github.com/async-rs/async-std/files/5258860/3ddcff0bcff64b8f8769056c7fa684e2-symbolicated.crash.zip)

**Comment by Keruspe** [comment]
I'm working on fixing this

**Comment by Keruspe** [comment]
From my testing, works fine both from within local and global tasks now

**Comment by Keruspe** [comment]
@sync while waiting for a release, if you declare a dependency on async-global-executor 1.2.1 with tokio02 feature enabled (as it's disabled by default), async-std should work properly
