### ISSUE TITLE
Not compiling with nightly-2020-09-22-x86_64-unknown-linux-gnu

### ISSUE THREAD

**Issue by jerry73204** [async-rs/async-std#883]
async-std does not compile with recent nightly toolchain (nightly-2020-09-22-x86_64-unknown-linux-gnu, to be exact). I personally downgrade the toolchain by `rustup default nightly-2020-09-21` to resolve this issue.

```
   --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.4/src/fs/open_options.rs:303:5
    |
303 |     impl OpenOptionsExt for OpenOptions {
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `as_flags` in implementation
    |
    = help: implement the missing item: `fn as_flags(&self) -> std::result::Result<i32, futures_io::Error> { todo!() }`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0046`.
error: could not compile `async-std`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by yoshuawuyts** [comment]
This is a regression on nightly, see https://github.com/rust-lang/rust/issues/77089 -- for now I recommend pinning to an earlier nightly as we wait on this to be resolved in the stdlib.

**Comment by tompro** [comment]
This currently also breaks docs.rs builds:
https://docs.rs/crate/redis_ts/0.2.0

**Comment by Fishrock123** [comment]
This is causing issues in downstream CI: https://github.com/http-rs/http-client/pull/45, https://github.com/http-rs/surf/pull/234

**Comment by jplatte** [comment]
Fixed in latest Nightly, via https://github.com/rust-lang/rust/pull/77090.

**Comment by jerry73204** [comment]
It is resolved in recent nightly. It's time to close this issue.
