### ISSUE TITLE
Book: unresolved import `futures::select`

### ISSUE THREAD

**Issue by SuperFluffy** [async-rs/async-std#89]
In the [current version](https://github.com/async-rs/async-std/blob/0156dc879bc67e313ef123978a8edfb24ae36fae/docs/src/tutorial/handling_disconnection.md) of the book, the final code of the Handling Disconnection tutorial doesn't work:

```rust
use futures::{
    channel::mpsc,
    SinkExt,
    FutureExt,
    select,
};

---

error[E0432]: unresolved import `futures::select`
  --> src/main.rs:13:5
   |
13 |     select,
   |     ^^^^^^ no `select` in the root
```

`futures-preview 0.3.0-alpha.17` actually defines two `select!` macros, `futures::future::select` and `futures::stream::select`, see [its `lib.rs`](https://github.com/rust-lang-nursery/futures-rs/blob/db1bafb064d3dc48befbf25b10efc370c1947c8e/futures/src/lib.rs).

Changing the import to `stream::select` (I hope I understood it correctly, given that we are working with streams; either way, importing `future::select` has the same issue) makes the import work, but it cannot resolve the macro still:

```rust
async fn client_writer(
    messages: &mut Receiver<String>,
    stream: Arc<TcpStream>,
    mut shutdown: Receiver<Void>,
) -> Result<()> {
    let mut stream = &*stream;
    loop {
        select! {
            msg = messages.next().fuse() => match msg {
                Some(msg) => stream.write_all(msg.as_bytes()).await?,
                None => break,
            },
            void = shutdown.next().fuse() => match void {
                Some(void) => match void {},
                None => break,
            }
        }
    }
    Ok(())
}

---

error: cannot find macro `select!` in this scope
  --> src/main.rs:92:9
   |
92 |         select! {
   |         ^^^^^^

error: cannot find macro `select!` in this scope
   --> src/main.rs:126:21
    |
126 |         let event = select! {
    |                     ^^^^^^

warning: unused import: `future::select`
  --> src/main.rs:13:5
   |
13 |     future::select,
   |     ^^^^^^^^^^^^^^
```

**Comment by taiki-e** [comment]
I think it needs to enable the futures crate's [`async-await` feature](https://github.com/rust-lang-nursery/futures-rs#feature-async-await).

```toml
[dependencies]
futures-preview = { version = "=0.3.0-alpha.18", features = ["async-await", "nightly"] }
```

https://rust-lang-nursery.github.io/futures-api-docs/0.3.0-alpha.18/futures/macro.select.html
> It is also gated behind the `async-await` feature of this library, which is *not* activated by default.

**Comment by SuperFluffy** [comment]
Yupp, that fixes it. Thank you for pointing it out.
