### ISSUE TITLE
Patterns collection for the book

### ISSUE THREAD

**Issue by skade** [async-rs/async-std#9]
# Splitting reader and writer on a stream

```rust
let (reader, writer) = &mut (&stream, &stream);
io::copy(reader, writer).await?;
```

**Comment by yoshuawuyts** [comment]
Perhaps we should add a "patterns" section at the end of the book? @skade is this something you'd like to pick up?

**Comment by stjepang** [comment]
I think it'd be good to have a "cookbook" or "common paterns" section in the book. Can we start by adding this example?

**Comment by yoshuawuyts** [comment]
We already have this section, but it's WIP: https://github.com/async-rs/async-std/commit/b6a453bd982bc1427258a2f4667c029b504544cd#diff-3dbd16223f25e8b5e0bcf099743107e9R28-R78

**Comment by stjepang** [comment]
Oh nice. I think we should just close this then and polish the book a bit.
