### ISSUE TITLE
Docs for task::spawn must mention support for tasks that block

### ISSUE THREAD

**Issue by jimblandy** [async-rs/async-std#905]
The async-std blog post ["stop worrying about async blocking"](https://async.rs/blog/stop-worrying-about-blocking-the-new-async-std-runtime/) explains that `spawn_blocking` is no longer needed, and that developers should simply use `spawn` instead and let the library decide whether it should keep the thread in the async pool.

If `task::spawn` is the recommended way to spawn tasks that may block, then users will write code that depends on that, and the design decision becomes something async-std can't revert without introducing bugs in its users. This is all fine (it seems like a good design to me), but non-obvious characteristics covered by async-std's stability guarantees should be documented.

**Comment by Keruspe** [comment]
Actually, this behaviour was never actually merged https://github.com/async-rs/async-std/pull/631

What I'm working on is an opt-in integration, disabled by default.

**Comment by jimblandy** [comment]
Since this isn't going to be the default behavior, this PR's documentation isn't appropriate. Documentation should be addressed as an integral part of whatever PR does get merged.
