### ISSUE TITLE
segmentation fault, x86_64-unknown-linux-musl

### ISSUE THREAD

**Issue by ktmlm** [async-rs/async-std#929]
I got `segmentation fault` like #662, on Alpine Linux(`x86_64-unknown-linux-musl`), at version v1.8.0 or v1.7.0.

All goes well on `x86_64-apple-darwin` or `x86_64-unknown-linux-gnu`.

When I switch to futures-v0.3.8 or tokio-v1.0.1, this problem remain.

**Only occur in debug mode !**

**Comment by skade** [comment]
@ktmlm do you have a small program that reproducibility triggers that bug?

**Comment by ktmlm** [comment]
This is caused by two async runtime embed together, that is a http server with an async runtime deps and a http client with an async runtime deps in the same thread.
