### ISSUE TITLE
Bug in basic file seek operations?

### ISSUE THREAD

**Issue by vlovich** [async-rs/async-std#939]
I'm doing a basic seek + write pattern. The async_std version appears to have a bug where the generated file (in the test code below) is 1526 bytes whereas it should be 1536 (1024 offset + 512 write). The regular non-async version of the same code generates a 1536-byte file (as does an equivalent C++ program I whipped up).

 on startup so careful if that's an important file for you) leading me to think the problem is somewhere in the async library (or in my usage of it although I don't see any obvious problems).

This is async-std 1.7.0 on MacOS 11.0.1.

Another (weird) thing I noticed is that the "10 bytes" that are missing can be controlled by varying the length of the first write for some reason. Additionally, if I change the last 512 byte write to have the values [0, 255] in a repeating pattern, we can observe, strangely, that the last 10 bytes of the 512 byte write are the bytes missing when viewed in hexdump on the generated file.

```
   // This test fails because the generated file is 1526 bytes instead of 1536.
    #[async_std::test]
    async fn test_async_file_io() {
        let mut file = async_std::fs::OpenOptions::new()
            .read(true)
            .write(true)
            .create(true)
            .truncate(true)
            .open("async_test.bin")
            .await
            .unwrap();

        let contents = [5; 10];
        file.seek(SeekFrom::Start(0)).await.unwrap();
        file.write(&contents).await.unwrap();
        file.flush().await.unwrap();

        let contents = [7; 4];
        file.seek(SeekFrom::Start(20)).await.unwrap();
        file.write(&contents).await.unwrap();
        file.flush().await.unwrap();

        let contents = [6; 5];
        file.seek(SeekFrom::Start(512 + 10)).await.unwrap();
        file.write(&contents).await.unwrap();
        file.flush().await.unwrap();

        let contents = [0xff; 512];
        file.seek(SeekFrom::Start(1024)).await.unwrap();
        file.write(&contents).await.unwrap();
        file.flush().await.unwrap();

        assert_eq!(1024 + 512, file.metadata().await.unwrap().len());
    }

    // This passes without issue.
    #[test]
    fn test_file_io() {
        use std::fs::File;
        use std::fs::OpenOptions;
        use std::io::Write;
        use std::io::Seek;

        let mut file = OpenOptions::new()
            .read(true)
            .write(true)
            .create(true)
            .truncate(true)
            .open("sync_test.bin")
            .unwrap();

        let contents = [5; 10];
        file.seek(std::io::SeekFrom::Start(0)).unwrap();
        file.write(&contents).unwrap();
        file.flush().unwrap();

        let contents = [7; 4];
        file.seek(std::io::SeekFrom::Start(20)).unwrap();
        file.write(&contents).unwrap();
        file.flush().unwrap();

        let contents = [6; 5];
        file.seek(std::io::SeekFrom::Start(512 + 10)).unwrap();
        file.write(&contents).unwrap();
        file.flush().unwrap();

        let contents = [0xff; 512];
        file.seek(std::io::SeekFrom::Start(1024)).unwrap();
        file.write(&contents).unwrap();
        file.flush().unwrap();

        assert_eq!(1024 + 512, file.metadata().unwrap().len());
    }
```

Sample C++ program doing the same thing with no problem:

```
#include <cstdio>
#include <fcntl.h>
#include <sys/types.h>
#include <unistd.h>
#include <sys/stat.h>
#include <unistd.h>
#include <vector>


int main() {
  unlink("test.bin");
  int fd = open("test.bin", O_CREAT | O_TRUNC | O_RDWR);

  std::vector<uint8_t> contents;

  contents.assign(10, 5);
  lseek(fd, 0, SEEK_SET);
  write(fd, contents.data(), contents.size());

  contents.assign(4, 7);
  lseek(fd, 20, SEEK_SET);
  write(fd, contents.data(), contents.size());

  contents.assign(5, 6);
  lseek(fd, 512, SEEK_SET);
  write(fd, contents.data(), contents.size());

  contents.assign(512, 0xff);
  lseek(fd, 1024, SEEK_SET);
  write(fd, contents.data(), contents.size());

  struct stat s;
  fstat(fd, &s);

  fprintf(stderr, "Length is now %lu\n", (long unsigned)s.st_size);
}
```

**Comment by Keruspe** [comment]
After stracing this, it appears that the syscalls are the same in both *but* the last write is indeed a write of 502 bytes instead of 512. Not that we request a write of 502, we're not requesting 512, which is the very odd part here

**Comment by Keruspe** [comment]
The missing bytes are indeed the length of the first write *or 8, if the first write is less than that*

**Comment by Keruspe** [comment]
Ok, after digging, I found why this doesn't work.

Write doesn't ensure we're writing everything you give it. It returns how many bytes have been written, and you're supposed to check that, and retry the remaining bytes, if any. async-std uses an intermediate buffer for async io, and you're hitting a point where this cache gets full, then the actual write syscall is called and we return how much we wrote (which isn't the complete buffer).

If you want to make sure everything gets writter, you should be using write_all. Using write all, everything works as expected.

**Comment by vlovich** [comment]
Oh wow. I’m surprised I overlooked that since that’s a pretty common pattern for write. I think I just assumed that write would return an error if it was partial. Apologies and thanks for identifying my bug and wasting your time.

I now have a wish that the API would return OK only if the write succeeded fully and an appropriate error enum be returned if the write was partial/empty so that unwrap would at least panic on misuse vs silently failing. Since this API is just mirroring the std API, is it even possible to rectify this kind of defect? I think the std API missed an opportunity here to make the return more Rusty vs the traditional C API approach that’s been inherited. On the other hand, you could argue that a partial write is still a success state if it somehow results in more efficient code gen? I don’t have an intuition on if the “ok” path of a match statement is more efficient than the error state.

Anyway, that’s a bit of a rant but I’d love to hear your thoughts even if there’s no change so I can build a better intuition here (I’m kind of new to Rust so still learning my way around).
