### ISSUE TITLE
Async-std JoinHandle.cancel() vs Tokio JoinHandle.abort() using a vector of handles

### ISSUE THREAD

**Issue by Eygem** [async-rs/async-std#958]
Hi, I have developed an embedded system where handles of spawned tasks are stored in a vector of handles. With Tokio I can borrow the vector and terminate a task using abort() on the handle. Instead with Async-std I am unable to do the same using cancel() as I am encountering an error.

These are two simple examples. The first one uses Tokio and runs w/o issues:
```rust
#[tokio::main]
async fn main() {

   let mut handles = Vec::new();

   handles.push(tokio::task::spawn(async {  }));
   handles.push(tokio::task::spawn(async {  }));

   for handle in &handles {
       // in Tokio abort() is: pub fn abort(&self)
       handle.abort();
   }

   println!("keep using vector after borrowing ... {:?}", handles);

}
```
The second one uses Async-std
```rust
#[async_std::main]
async fn main() {

    let mut handles = Vec::new();

    handles.push(async_std::task::spawn(async {  }));
    handles.push(async_std::task::spawn(async {  }));

    for handle in &handles {
        // in Async-std cancel() is: pub async fn cancel(self) -> Option<T>
        handle.cancel().await;
    }
 
    println!("keep using vector after borrowing ... {:?}", handles);

}
```
and produces the following error:
```
 handle.cancel().await;
   |         ^^^^^^ move occurs because `*handle` has type `async_std::task::JoinHandle<()>`, 
which does not implement the `Copy` trait
```
Do you have any idea if a workaround exists to achieve the same result? Otherwise you may wish to consider it as a proposal for an enhancement of cancel() function.
Many thanks for your help!

**Comment by yoshuawuyts** [comment]
[`JoinHandle::cancel`](https://docs.rs/async-std/1.9.0/async_std/task/struct.JoinHandle.html#method.cancel) consumes `self`. The reason for this is that after a join handle has been canceled, it no longer holds any references to tasks and is considered "finished" -- much like the way [`std::mem::drop`](https://doc.rust-lang.org/std/mem/fn.drop.html) also consumes values.

Instead of iterating over references, consider iterating over owned values instead:

```rust
#[async_std::main]
async fn main() {

    let mut handles = Vec::new();

    handles.push(async_std::task::spawn(async {  }));
    handles.push(async_std::task::spawn(async {  }));

    for handle in handles.into_iter() { // iterate over owned handles here instead
        // in Async-std cancel() is: pub async fn cancel(self) -> Option<T>
        handle.cancel().await;
    }
 
    println!("keep using vector after borrowing ... {:?}", handles);
}
```

**Comment by Eygem** [comment]
Hi Yoshua, thank you very much for your kind feedback. Yes, I realised from joinhandle::cancel function declaration it consumes ```self```, while Tokio joinhandle::abort doesn't. In my case it complicates a bit, but I agree it makes sense.
I do not need to keep the empty vector, it was just a simple (probably too simple!) example to show the different behaviour between Async-std and Tokio. 

I use a vector to associate tasks' handles with IO Ports of an embedded system. Before spawning a new task on the IO Port, the ongoing one, if any, is cancelled. This vector is passed by reference multiple times, depending on the commands received, so I cannot consume the vector. 

I came out with the following workaround, passing the vector by reference, but working on the owned handle each time. I remove the handle from the vector, then cancel it, and at the end replace it with the new one. 
```
use async_std::task::JoinHandle;
use std::time::Duration;

#[async_std::main]
async fn main() {

    let mut handles = Vec::new();
    handles.push(None); // IO Port 0 associated task
    handles.push(Some(async_std::task::spawn(async {  }))); // IO Port 1 associated task

    toggle_command(0, &mut handles).await; // IO Port 0 Blinck
    async_std::task::sleep(Duration::from_secs(10)).await;
    pwm_command(0, &mut handles).await; // IO Port 0 PWM burst
}

async fn toggle_command(port_id: usize, handles: &mut Vec<Option<JoinHandle<()>>>) {
    if let Some(handle) = handles.remove(port_id) {
        handle.cancel().await; // Abort current task on IO Port, if any
    }
    let new_handle = Some(async_std::task::spawn(async {  })); //Spawn Blinck task on IO Port
    handles.insert(port_id, new_handle);
}

async fn pwm_command(port_id: usize, handles: &mut Vec<Option<JoinHandle<()>>>) {
    if let Some(handle) = handles.remove(port_id) {
        handle.cancel().await; // Abort current task on IO Port, if any
    }
    let new_handle = Some(async_std::task::spawn(async {  })); //Spawn Pwm task on IO Port
    handles.insert(port_id, new_handle);
}
```
Thank you again and congratulations for Async-std !! It's a very powerful tool !
