### ISSUE TITLE
async-std violates API guidelines' "C-STABLE"

### ISSUE THREAD

**Issue by taiki-e** [async-rs/async-std#959]
https://rust-lang.github.io/api-guidelines/necessities.html#public-dependencies-of-a-stable-crate-are-stable-c-stable

> ### Public dependencies of a stable crate are stable (C-STABLE)
> A crate cannot be stable (>=1.0.0) without all of its public dependencies being stable.

**Comment by yoshuawuyts** [comment]
"guidelines" aren't "rules". They're suggestions, which in this case exist to minimize the amount of churn a project goes through. The intent matters, and framing it as if `async-std` has broken some sort of rule it shouldn't have is plain wrong.

In our case we've chosen to make the trade-off to rely on `futures-core` 0.3, with the knowledge that if a breaking change was published we would need to upgrade too. This is an acceptable strategy and compliant with semver.

However this is clearly in response to our conversation on the futures-rs repo. I don't think I'm overreaching in questioning the need for breaking changes in the first place, nor my ask for clear motivation of each breaking change, and highlighting the impact breaking changes will have on the wider ecosystem.

But it's a Sunday here and don't want to get deeper into this argument. For now I'm going to close this issue, and ask that we continue the conversation next week on the futures-rs issues and Zulip.
