### ISSUE TITLE
Transform TcpListener into Stream of connections

### ISSUE THREAD

**Issue by piegamesde** [async-rs/async-std#981]
There is [`TcpListener::incoming`](https://docs.rs/async-std/1.9.0/async_std/net/struct.TcpListener.html#method.incoming) that provides this functionality, but it has a lifetime. I cannot simply pass the stream around and manipulate it, because it has `'a` lifetime bound to the `TcpListener`. An alternative that takes over ownership would be appreciated.

Note that this is symmetric to the stdlib, where the same API suffers from the same problem.

**Comment by Fishrock123** [comment]
A solution should ideally first be found for the problem in stdlib since async-std tries to mirror the stdlib in async ways.

**Comment by piegamesde** [comment]
The feature got merged, so it could already be implemented behind an unstable flag.

**Comment by yoshuawuyts** [comment]
> The feature got merged, so it could already be implemented behind an unstable flag.

Adding this behind an unstable flag makes sense to me! Would you be willing to a file a PR for that?

**Comment by piegamesde** [comment]
Ugh, apparently since all methods are delegated to `Async`, I need to make a pull request to `async_io` first?
