### ISSUE TITLE
Link to the `channel` documentation in `sync` page is broken

### ISSUE THREAD

**Issue by cagatay-y** [async-rs/async-std#983]
[Documentation page for the `sync` module](https://docs.rs/async-std/1.10.0/async_std/sync/index.html) links to the `channel` function which was removed in the last version.
I originally intended to open a PR with a fix but I am not sure whether it would be more appropriate to change the link to the new `channel` module, or remove the link altogether since the functionality is moved from `sync`.

**Comment by yoshuawuyts** [comment]
@cagatay-y thanks for opening this! -- We probably should remove the existing mention of channels, and instead mention something like: "if you're looking for channels, check out `async_std::channel`. Would you be willing to open a PR for that?
