### ISSUE TITLE
Tokio comparison

### ISSUE THREAD

**Issue by bugproof** [async-rs/async-std#992]
I think having such comparison would be very helpful for people new to Rust trying to understand async ecosystem mess. Why would I want to use async-std over tokio? How can I answer this question?

https://www.reddit.com/r/rust/comments/l1rnn6/is_asyncstd_a_second_class_citizen/

**Comment by wodny** [comment]
And what might be even more important - is the project dead?

**Comment by wodny** [comment]
> Anyway, this is probably more of an answer than you were expecting.

This kind of answer is great. Thank you very much for that. It gives context, an actual insight and allows for a proper interpretation of project/repository statistics, otherwise hard to evaluate.

**Comment by zzy** [comment]
@yoshuawuyts Great answer. Thank you!
